import { initContract } from "@ts-rest/core";
import { z } from "zod";
import {
  AcceptAiSummaryBody,
  AdvanceAuditBody,
  AdvanceCapaBody,
  AiDraftDto,
  AiDraftRequest,
  AiSummaryDto,
  AssignCapaBody,
  AssignEightDBody,
  AssignInspectionBody,
  AssignNcrBody,
  AssignScarBody,
  AuditDto,
  AuditFindingDto,
  CapaActionDto,
  CapaDto,
  CreateAuditBody,
  CreateAuditFindingBody,
  CompleteFileBody,
  CompleteInspectionBody,
  CreateCapaActionBody,
  CreateCapaBody,
  CreateDocumentBody,
  CreateFindingBody,
  CreateInspectionBody,
  CreateNcrActionBody,
  CreateNcrBody,
  CreateTemplateBody,
  CreateEightDBody,
  CreateExportBody,
  DocumentDto,
  DocumentVersionDto,
  DownloadFileQuery,
  DownloadFileResult,
  EightDDto,
  ExportDto,
  FileDto,
  FindingDto,
  InspectionDto,
  MeDto,
  WorkspacesDto,
  WorkspaceDto,
  SwitchWorkspaceBody,
  MemberDto,
  NcrActionDto,
  NcrDto,
  CountDto,
  NewDocumentVersionBody,
  NotificationDto,
  NotificationPrefsDto,
  StarNotificationBody,
  PresignFileBody,
  PresignFileResult,
  AuditEventDto,
  CommentDto,
  CreateCommentBody,
  CreateEntityLinkBody,
  EntityLinkDto,
  EntityRefQuery,
  RaiseCapaFromFindingBody,
  RaiseNcrFromFindingBody,
  ReviewDocumentBody,
  SearchResults,
  UnreadCountDto,
  UpdateEightDStepBody,
  UpdateNotificationPrefsBody,
  RevertCapaBody,
  ScorecardWeightsQuery,
  SetRecurrenceBody,
  StartInspectionBody,
  SupplierDto,
  CreateSupplierBody,
  UpdateSupplierBody,
  PpapSubmissionDto,
  CreatePpapBody,
  UpdatePpapBody,
  UpdatePpapElementBody,
  PpapDecisionBody,
  ScarDto,
  CreateScarBody,
  UpdateScarBody,
  AdvanceScarBody,
  AcknowledgeScarBody,
  ScarChargebackBody,
  PortalIdentityDto,
  PortalScarDto,
  PortalPpapDto,
  PortalScarRespondBody,
  PortalPpapResubmitBody,
  PortalEvidencePresignBody,
  BrandingDto,
  UpdateBrandingBody,
  SessionPolicyDto,
  UpdateSessionPolicyBody,
  NcrValidationRuleDto,
  CreateNcrValidationRuleBody,
  UpdateNcrValidationRuleBody,
  LegalHoldDto,
  CreateLegalHoldBody,
  UpdateLegalHoldBody,
  DlpPolicyDto,
  CreateDlpPolicyBody,
  UpdateDlpPolicyBody,
  CostCenterDto,
  CreateCostCenterBody,
  UpdateCostCenterBody,
  CostCenterAssignmentDto,
  AssignCostCenterBody,
  ChargebackSettingsDto,
  UpdateChargebackSettingsBody,
  ChargebackReportDto,
  TemplateDto,
  TransitionDocumentBody,
  TransitionEightDBody,
  TransitionNcrBody,
  UpdateCapaActionStatusBody,
  UpdateNcrActionStatusBody,
  VerifyNcrBody,
} from "./dto.js";
import { ErrorBody, PageQuery, page } from "./http.js";
import {
  AuditPhase,
  AuditType,
  CapaPhase,
  CapaType,
  DocumentCategory,
  DocumentStatus,
  EightDStatus,
  ExportResource,
  ExportStatus,
  InspectionStatus,
  NcrPriority,
  NcrStatus,
  PpapStatus,
  ScarSeverity,
  ScarStatus,
  RiskLevel,
  SupplierStatus,
  TemplateStatus,
} from "./enums.js";

/**
 * The API contract (03 §1) — contract-first, in `packages/types` so it is the
 * one artifact the server, the OpenAPI document, and the typed client all
 * derive from. The Nest handlers validate their inputs against these very
 * schemas; the web client is `initClient(contract)`. Neither side can drift
 * from the other because there is only one definition.
 */

const c = initContract();

/** Errors any authenticated route may return. Declared once, spread per route. */
const commonErrors = {
  400: ErrorBody,
  401: ErrorBody,
  403: ErrorBody,
  404: ErrorBody,
  409: ErrorBody,
  422: ErrorBody,
  429: ErrorBody,
} as const;

export const contract = c.router(
  {
    getMe: {
      method: "GET",
      path: "/v1/me",
      responses: { 200: MeDto, 401: ErrorBody },
      summary: "The current session's identity and capabilities",
    },
    myWorkspaces: {
      method: "GET",
      path: "/v1/me/workspaces",
      responses: { 200: WorkspacesDto, ...commonErrors },
      summary: "Every workspace the signed-in person belongs to (the switcher)",
    },
    switchWorkspace: {
      method: "POST",
      path: "/v1/me/switch-workspace",
      body: SwitchWorkspaceBody,
      responses: { 200: WorkspaceDto, ...commonErrors },
      summary: "Switch the active workspace (mints a session in the target tenant)",
    },

    // --- Members directory -------------------------------------------------
    listMembers: {
      method: "GET",
      path: "/v1/members",
      query: PageQuery,
      responses: { 200: page(MemberDto), ...commonErrors },
      summary: "List this tenant's members (id → name + role) so the UI can resolve people",
    },

    // --- Search ------------------------------------------------------------
    search: {
      method: "GET",
      path: "/v1/search",
      query: z.object({ q: z.string().min(1).max(200) }),
      responses: { 200: SearchResults, ...commonErrors },
      summary: "Federated full-text search across records (top 6 per kind), plant-scoped by role",
    },

    // --- Inspection templates ---------------------------------------------
    listTemplates: {
      method: "GET",
      path: "/v1/inspection-templates",
      query: PageQuery.extend({ status: TemplateStatus.optional() }),
      responses: { 200: page(TemplateDto), ...commonErrors },
      summary: "List inspection templates (cursor-paginated)",
    },
    createTemplate: {
      method: "POST",
      path: "/v1/inspection-templates",
      body: CreateTemplateBody,
      responses: { 201: TemplateDto, ...commonErrors },
      summary: "Create a draft template",
    },
    getTemplate: {
      method: "GET",
      path: "/v1/inspection-templates/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: TemplateDto, ...commonErrors },
      summary: "Fetch one template (with its form schema)",
    },
    publishTemplate: {
      method: "POST",
      path: "/v1/inspection-templates/:id/publish",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({ version: z.number().int().nonnegative() }),
      responses: { 200: TemplateDto, ...commonErrors },
      summary: "Publish a draft template (makes its schema immutable)",
    },

    // --- Inspections -------------------------------------------------------
    listInspections: {
      method: "GET",
      path: "/v1/inspections",
      query: PageQuery.extend({
        status: InspectionStatus.optional(),
        plantId: z.string().uuid().optional(),
      }),
      responses: { 200: page(InspectionDto), ...commonErrors },
      summary: "List inspections (cursor-paginated, plant-scoped by role)",
    },
    createInspection: {
      method: "POST",
      path: "/v1/inspections",
      body: CreateInspectionBody,
      responses: { 201: InspectionDto, ...commonErrors },
      summary: "Schedule an inspection from a published template",
    },
    getInspection: {
      method: "GET",
      path: "/v1/inspections/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: InspectionDto, ...commonErrors },
      summary: "Fetch one inspection",
    },
    startInspection: {
      method: "POST",
      path: "/v1/inspections/:id/start",
      pathParams: z.object({ id: z.string().uuid() }),
      body: StartInspectionBody,
      responses: { 200: InspectionDto, ...commonErrors },
      summary: "Begin an inspection (scheduled → in_progress)",
    },
    completeInspection: {
      method: "POST",
      path: "/v1/inspections/:id/complete",
      pathParams: z.object({ id: z.string().uuid() }),
      body: CompleteInspectionBody,
      responses: { 200: InspectionDto, ...commonErrors },
      summary: "Submit responses, validate + score, and complete an inspection",
    },
    setInspectionRecurrence: {
      method: "PUT",
      path: "/v1/inspections/:id/recurrence",
      pathParams: z.object({ id: z.string().uuid() }),
      body: SetRecurrenceBody,
      responses: { 200: InspectionDto, ...commonErrors },
      summary: "Set, change, or clear a series head's recurrence (06 materialises occurrences)",
    },
    assignInspection: {
      method: "POST",
      path: "/v1/inspections/:id/assign",
      pathParams: z.object({ id: z.string().uuid() }),
      body: AssignInspectionBody,
      responses: { 200: InspectionDto, ...commonErrors },
      summary: "Assign, reassign, or clear an inspection's inspector (audited)",
    },
    listInspectionOccurrences: {
      method: "GET",
      path: "/v1/inspections/:id/occurrences",
      pathParams: z.object({ id: z.string().uuid() }),
      query: PageQuery,
      responses: { 200: page(InspectionDto), ...commonErrors },
      summary: "List a recurring series' materialised occurrences",
    },

    // --- Findings ----------------------------------------------------------
    listFindings: {
      method: "GET",
      path: "/v1/inspections/:id/findings",
      pathParams: z.object({ id: z.string().uuid() }),
      query: PageQuery,
      responses: { 200: page(FindingDto), ...commonErrors },
      summary: "List an inspection's findings",
    },
    createFinding: {
      method: "POST",
      path: "/v1/inspections/:id/findings",
      pathParams: z.object({ id: z.string().uuid() }),
      body: CreateFindingBody,
      responses: { 201: FindingDto, ...commonErrors },
      summary: "Record a finding against an inspection",
    },

    // --- NCRs --------------------------------------------------------------
    listNcrs: {
      method: "GET",
      path: "/v1/ncrs",
      query: PageQuery.extend({
        status: NcrStatus.optional(),
        priority: NcrPriority.optional(),
        plantId: z.string().uuid().optional(),
      }),
      responses: { 200: page(NcrDto), ...commonErrors },
      summary: "List NCRs (cursor-paginated, plant-scoped by role)",
    },
    createNcr: {
      method: "POST",
      path: "/v1/ncrs",
      body: CreateNcrBody,
      responses: { 201: NcrDto, ...commonErrors },
      summary: "Raise an NCR (optionally from a finding)",
    },
    getNcr: {
      method: "GET",
      path: "/v1/ncrs/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: NcrDto, ...commonErrors },
      summary: "Fetch one NCR",
    },
    transitionNcr: {
      method: "POST",
      path: "/v1/ncrs/:id/transition",
      pathParams: z.object({ id: z.string().uuid() }),
      body: TransitionNcrBody,
      responses: { 200: NcrDto, ...commonErrors },
      summary: "Advance an NCR through its lifecycle (assign, start, resolve, close, escalate, reopen)",
    },
    verifyNcr: {
      method: "POST",
      path: "/v1/ncrs/:id/verify",
      pathParams: z.object({ id: z.string().uuid() }),
      body: VerifyNcrBody,
      responses: { 200: NcrDto, ...commonErrors },
      summary: "Verify a resolved NCR (four-eyes: not the resolver)",
    },
    assignNcr: {
      method: "POST",
      path: "/v1/ncrs/:id/assign",
      pathParams: z.object({ id: z.string().uuid() }),
      body: AssignNcrBody,
      responses: { 200: NcrDto, ...commonErrors },
      summary: "Assign, reassign, or clear an NCR's owner (audited)",
    },

    // --- NCR corrective actions -------------------------------------------
    listNcrActions: {
      method: "GET",
      path: "/v1/ncrs/:id/actions",
      pathParams: z.object({ id: z.string().uuid() }),
      query: PageQuery,
      responses: { 200: page(NcrActionDto), ...commonErrors },
      summary: "List an NCR's corrective/preventive actions",
    },
    createNcrAction: {
      method: "POST",
      path: "/v1/ncrs/:id/actions",
      pathParams: z.object({ id: z.string().uuid() }),
      body: CreateNcrActionBody,
      responses: { 201: NcrActionDto, ...commonErrors },
      summary: "Add a corrective/preventive/containment action to an NCR",
    },
    updateNcrActionStatus: {
      method: "POST",
      path: "/v1/ncr-actions/:id/status",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdateNcrActionStatusBody,
      responses: { 200: NcrActionDto, ...commonErrors },
      summary: "Advance an action's status (pending → in_progress → done → verified)",
    },

    // --- 8D ----------------------------------------------------------------
    listEightDs: {
      method: "GET",
      path: "/v1/eight-ds",
      query: PageQuery.extend({
        status: EightDStatus.optional(),
        ncrId: z.string().uuid().optional(),
      }),
      responses: { 200: page(EightDDto), ...commonErrors },
      summary: "List 8D reports (cursor-paginated)",
    },
    createEightD: {
      method: "POST",
      path: "/v1/eight-ds",
      body: CreateEightDBody,
      responses: { 201: EightDDto, ...commonErrors },
      summary: "Open an 8D (optionally from an NCR, which it then blocks from closing)",
    },
    getEightD: {
      method: "GET",
      path: "/v1/eight-ds/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: EightDDto, ...commonErrors },
      summary: "Fetch one 8D with its disciplines",
    },
    updateEightDStep: {
      method: "POST",
      path: "/v1/eight-ds/:id/steps/:step",
      pathParams: z.object({ id: z.string().uuid(), step: z.coerce.number().int().min(1).max(8) }),
      body: UpdateEightDStepBody,
      responses: { 200: EightDDto, ...commonErrors },
      summary: "Update a discipline (D1–D8); completing one is gated by its prerequisites",
    },
    transitionEightD: {
      method: "POST",
      path: "/v1/eight-ds/:id/transition",
      pathParams: z.object({ id: z.string().uuid() }),
      body: TransitionEightDBody,
      responses: { 200: EightDDto, ...commonErrors },
      summary: "Complete (all disciplines done) or cancel an 8D",
    },
    assignEightD: {
      method: "POST",
      path: "/v1/eight-ds/:id/assign",
      pathParams: z.object({ id: z.string().uuid() }),
      body: AssignEightDBody,
      responses: { 200: EightDDto, ...commonErrors },
      summary: "Assign, reassign, or clear an 8D's team lead and/or champion (audited)",
    },

    // --- Audits ------------------------------------------------------------
    listAudits: {
      method: "GET",
      path: "/v1/audits",
      query: PageQuery.extend({
        status: AuditPhase.optional(),
        type: AuditType.optional(),
        plantId: z.string().uuid().optional(),
      }),
      responses: { 200: page(AuditDto), ...commonErrors },
      summary: "List audits (cursor-paginated, plant-scoped by role)",
    },
    createAudit: {
      method: "POST",
      path: "/v1/audits",
      body: CreateAuditBody,
      responses: { 201: AuditDto, ...commonErrors },
      summary: "Schedule an audit",
    },
    getAudit: {
      method: "GET",
      path: "/v1/audits/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: AuditDto, ...commonErrors },
      summary: "Fetch one audit",
    },
    advanceAudit: {
      method: "POST",
      path: "/v1/audits/:id/advance",
      pathParams: z.object({ id: z.string().uuid() }),
      body: AdvanceAuditBody,
      responses: { 200: AuditDto, ...commonErrors },
      summary: "Advance an audit one phase forward",
    },
    listAuditFindings: {
      method: "GET",
      path: "/v1/audits/:id/findings",
      pathParams: z.object({ id: z.string().uuid() }),
      query: PageQuery,
      responses: { 200: page(AuditFindingDto), ...commonErrors },
      summary: "List an audit's findings",
    },
    createAuditFinding: {
      method: "POST",
      path: "/v1/audits/:id/findings",
      pathParams: z.object({ id: z.string().uuid() }),
      body: CreateAuditFindingBody,
      responses: { 201: AuditFindingDto, ...commonErrors },
      summary: "Record a finding against an audit",
    },
    raiseNcrFromAuditFinding: {
      method: "POST",
      path: "/v1/audit-findings/:id/raise-ncr",
      pathParams: z.object({ id: z.string().uuid() }),
      body: RaiseNcrFromFindingBody,
      responses: { 201: NcrDto, ...commonErrors },
      summary: "Raise an NCR from an audit finding (links the finding)",
    },
    raiseCapaFromAuditFinding: {
      method: "POST",
      path: "/v1/audit-findings/:id/raise-capa",
      pathParams: z.object({ id: z.string().uuid() }),
      body: RaiseCapaFromFindingBody,
      responses: { 201: CapaDto, ...commonErrors },
      summary: "Raise a CAPA from an audit finding (links the finding)",
    },

    // --- Exports -----------------------------------------------------------
    listExports: {
      method: "GET",
      path: "/v1/exports",
      query: PageQuery.extend({
        resource: ExportResource.optional(),
        status: ExportStatus.optional(),
      }),
      responses: { 200: page(ExportDto), ...commonErrors },
      summary: "List exports (cursor-paginated, newest first)",
    },
    createExport: {
      method: "POST",
      path: "/v1/exports",
      body: CreateExportBody,
      // 202: the render runs on the `reports` queue; poll getExport for the URL.
      responses: { 202: ExportDto, ...commonErrors },
      summary: "Request an async export (returns 202; poll for the download URL)",
    },
    getExport: {
      method: "GET",
      path: "/v1/exports/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: ExportDto, ...commonErrors },
      summary: "Fetch an export's status (with a presigned URL once completed)",
    },

    // --- AI gateway (06 §3) ------------------------------------------------
    requestAiDraft: {
      method: "POST",
      path: "/v1/ai/drafts",
      body: AiDraftRequest,
      // 402: pack inactive or budget exhausted; 503: model provider unavailable.
      responses: { 200: AiDraftDto, 402: ErrorBody, 503: ErrorBody, ...commonErrors },
      summary: "Request an AI draft through the governed gateway (never writes an entity)",
    },
    acceptAiSummary: {
      method: "POST",
      path: "/v1/ai/summaries/accept",
      body: AcceptAiSummaryBody,
      responses: { 200: AiSummaryDto, ...commonErrors },
      summary: "Accept an AI-drafted summary onto a document (records ai_draft_accepted)",
    },

    // --- CAPAs -------------------------------------------------------------
    listCapas: {
      method: "GET",
      path: "/v1/capas",
      query: PageQuery.extend({
        status: CapaPhase.optional(),
        type: CapaType.optional(),
        priority: NcrPriority.optional(),
      }),
      responses: { 200: page(CapaDto), ...commonErrors },
      summary: "List CAPAs (cursor-paginated)",
    },
    createCapa: {
      method: "POST",
      path: "/v1/capas",
      body: CreateCapaBody,
      responses: { 201: CapaDto, ...commonErrors },
      summary: "Open a CAPA",
    },
    getCapa: {
      method: "GET",
      path: "/v1/capas/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: CapaDto, ...commonErrors },
      summary: "Fetch one CAPA",
    },
    advanceCapa: {
      method: "POST",
      path: "/v1/capas/:id/advance",
      pathParams: z.object({ id: z.string().uuid() }),
      body: AdvanceCapaBody,
      responses: { 200: CapaDto, ...commonErrors },
      summary: "Advance a CAPA one phase forward",
    },
    revertCapa: {
      method: "POST",
      path: "/v1/capas/:id/revert",
      pathParams: z.object({ id: z.string().uuid() }),
      body: RevertCapaBody,
      responses: { 200: CapaDto, ...commonErrors },
      summary: "Revert a CAPA to an earlier phase (audited, reason required)",
    },
    assignCapa: {
      method: "POST",
      path: "/v1/capas/:id/assign",
      pathParams: z.object({ id: z.string().uuid() }),
      body: AssignCapaBody,
      responses: { 200: CapaDto, ...commonErrors },
      summary: "Assign, reassign, or clear a CAPA's owner and/or sponsor (audited)",
    },

    // --- CAPA actions ------------------------------------------------------
    listCapaActions: {
      method: "GET",
      path: "/v1/capas/:id/actions",
      pathParams: z.object({ id: z.string().uuid() }),
      query: PageQuery,
      responses: { 200: page(CapaActionDto), ...commonErrors },
      summary: "List a CAPA's actions",
    },
    createCapaAction: {
      method: "POST",
      path: "/v1/capas/:id/actions",
      pathParams: z.object({ id: z.string().uuid() }),
      body: CreateCapaActionBody,
      responses: { 201: CapaActionDto, ...commonErrors },
      summary: "Add an action to a CAPA",
    },
    updateCapaActionStatus: {
      method: "POST",
      path: "/v1/capa-actions/:id/status",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdateCapaActionStatusBody,
      responses: { 200: CapaActionDto, ...commonErrors },
      summary: "Advance a CAPA action's status (pending → in_progress → done → verified)",
    },

    // --- Documents ---------------------------------------------------------
    listDocuments: {
      method: "GET",
      path: "/v1/documents",
      query: PageQuery.extend({
        status: DocumentStatus.optional(),
        category: DocumentCategory.optional(),
      }),
      responses: { 200: page(DocumentDto), ...commonErrors },
      summary: "List documents (cursor-paginated)",
    },
    createDocument: {
      method: "POST",
      path: "/v1/documents",
      body: CreateDocumentBody,
      responses: { 201: DocumentDto, ...commonErrors },
      summary: "Create a document (draft, version 1.0)",
    },
    getDocument: {
      method: "GET",
      path: "/v1/documents/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: DocumentDto, ...commonErrors },
      summary: "Fetch one document",
    },
    transitionDocument: {
      method: "POST",
      path: "/v1/documents/:id/transition",
      pathParams: z.object({ id: z.string().uuid() }),
      body: TransitionDocumentBody,
      responses: { 200: DocumentDto, ...commonErrors },
      summary: "Author-side lifecycle: submit (→pending), revise (rejected→draft), archive",
    },
    reviewDocument: {
      method: "POST",
      path: "/v1/documents/:id/review",
      pathParams: z.object({ id: z.string().uuid() }),
      body: ReviewDocumentBody,
      responses: { 200: DocumentDto, ...commonErrors },
      summary: "Approve or reject a pending document (four-eyes: not the author)",
    },
    listDocumentVersions: {
      method: "GET",
      path: "/v1/documents/:id/versions",
      pathParams: z.object({ id: z.string().uuid() }),
      query: PageQuery,
      responses: { 200: page(DocumentVersionDto), ...commonErrors },
      summary: "List a document's version history",
    },
    newDocumentVersion: {
      method: "POST",
      path: "/v1/documents/:id/versions",
      pathParams: z.object({ id: z.string().uuid() }),
      body: NewDocumentVersionBody,
      responses: { 201: DocumentDto, ...commonErrors },
      summary: "Open a new draft version of an approved document",
    },

    // --- Collaboration: comments, links, access log ------------------------
    listComments: {
      method: "GET",
      path: "/v1/comments",
      query: EntityRefQuery.merge(PageQuery),
      responses: { 200: page(CommentDto), ...commonErrors },
      summary: "List a record's comments (cursor-paginated, newest first)",
    },
    createComment: {
      method: "POST",
      path: "/v1/comments",
      body: CreateCommentBody,
      responses: { 201: CommentDto, ...commonErrors },
      summary: "Post a comment on a record (audited as 'commented' on the record)",
    },
    deleteComment: {
      method: "POST",
      path: "/v1/comments/:id/delete",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: CommentDto, ...commonErrors },
      summary: "Soft-delete one of your own comments",
    },
    listAuditEvents: {
      method: "GET",
      path: "/v1/audit-events",
      query: EntityRefQuery.merge(PageQuery),
      responses: { 200: page(AuditEventDto), ...commonErrors },
      summary: "A record's access log (audit events, newest first; no payloads)",
    },
    listEntityLinks: {
      method: "GET",
      path: "/v1/entity-links",
      query: EntityRefQuery,
      responses: { 200: page(EntityLinkDto), ...commonErrors },
      summary: "List records linked to this record (either direction)",
    },
    createEntityLink: {
      method: "POST",
      path: "/v1/entity-links",
      body: CreateEntityLinkBody,
      responses: { 201: EntityLinkDto, ...commonErrors },
      summary: "Link two records (both must resolve within the tenant)",
    },
    deleteEntityLink: {
      method: "POST",
      path: "/v1/entity-links/:id/delete",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: EntityLinkDto, ...commonErrors },
      summary: "Remove a link between two records",
    },

    // --- Settings: white-label branding ------------------------------------
    getBranding: {
      method: "GET",
      path: "/v1/settings/branding",
      responses: { 200: BrandingDto, ...commonErrors },
      summary: "This workspace's white-label branding (defaults-merged, read by the shell)",
    },
    updateBranding: {
      method: "PUT",
      path: "/v1/settings/branding",
      body: UpdateBrandingBody,
      responses: { 200: BrandingDto, ...commonErrors },
      summary: "Save this workspace's white-label branding (settings:manage; optimistic)",
    },

    // --- Settings: session policy ------------------------------------------
    getSessionPolicy: {
      method: "GET",
      path: "/v1/settings/session-policy",
      responses: { 200: SessionPolicyDto, ...commonErrors },
      summary: "This workspace's session policy (defaults-merged)",
    },
    updateSessionPolicy: {
      method: "PUT",
      path: "/v1/settings/session-policy",
      body: UpdateSessionPolicyBody,
      responses: { 200: SessionPolicyDto, ...commonErrors },
      summary: "Save this workspace's session policy (settings:manage; optimistic)",
    },

    // --- Settings: NCR validation rules ------------------------------------
    listNcrValidationRules: {
      method: "GET",
      path: "/v1/settings/ncr-validation-rules",
      responses: { 200: page(NcrValidationRuleDto), ...commonErrors },
      summary: "The NCR validation rules enforced on NCR create",
    },
    createNcrValidationRule: {
      method: "POST",
      path: "/v1/settings/ncr-validation-rules",
      body: CreateNcrValidationRuleBody,
      responses: { 201: NcrValidationRuleDto, ...commonErrors },
      summary: "Add an NCR validation rule (settings:manage)",
    },
    updateNcrValidationRule: {
      method: "PUT",
      path: "/v1/settings/ncr-validation-rules/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdateNcrValidationRuleBody,
      responses: { 200: NcrValidationRuleDto, ...commonErrors },
      summary: "Edit an NCR validation rule (settings:manage; optimistic)",
    },
    deleteNcrValidationRule: {
      method: "POST",
      path: "/v1/settings/ncr-validation-rules/:id/delete",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: NcrValidationRuleDto, ...commonErrors },
      summary: "Remove an NCR validation rule (settings:manage)",
    },

    // --- Settings: legal hold register -------------------------------------
    listLegalHolds: {
      method: "GET",
      path: "/v1/settings/legal-holds",
      responses: { 200: page(LegalHoldDto), ...commonErrors },
      summary: "This workspace's legal-hold register",
    },
    createLegalHold: {
      method: "POST",
      path: "/v1/settings/legal-holds",
      body: CreateLegalHoldBody,
      responses: { 201: LegalHoldDto, ...commonErrors },
      summary: "Open a legal hold (settings:manage)",
    },
    updateLegalHold: {
      method: "PUT",
      path: "/v1/settings/legal-holds/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdateLegalHoldBody,
      responses: { 200: LegalHoldDto, ...commonErrors },
      summary: "Edit a legal hold (settings:manage; optimistic)",
    },
    releaseLegalHold: {
      method: "POST",
      path: "/v1/settings/legal-holds/:id/release",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({ version: z.number().int().nonnegative() }),
      responses: { 200: LegalHoldDto, ...commonErrors },
      summary: "Release a legal hold (settings:manage; optimistic)",
    },
    deleteLegalHold: {
      method: "POST",
      path: "/v1/settings/legal-holds/:id/delete",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: LegalHoldDto, ...commonErrors },
      summary: "Remove a legal hold from the register (settings:manage)",
    },

    // --- Settings: DLP policy register -------------------------------------
    listDlpPolicies: {
      method: "GET",
      path: "/v1/settings/dlp-policies",
      responses: { 200: page(DlpPolicyDto), ...commonErrors },
      summary: "This workspace's DLP policy register",
    },
    createDlpPolicy: {
      method: "POST",
      path: "/v1/settings/dlp-policies",
      body: CreateDlpPolicyBody,
      responses: { 201: DlpPolicyDto, ...commonErrors },
      summary: "Add a DLP policy (settings:manage)",
    },
    updateDlpPolicy: {
      method: "PUT",
      path: "/v1/settings/dlp-policies/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdateDlpPolicyBody,
      responses: { 200: DlpPolicyDto, ...commonErrors },
      summary: "Edit a DLP policy (settings:manage; optimistic)",
    },
    deleteDlpPolicy: {
      method: "POST",
      path: "/v1/settings/dlp-policies/:id/delete",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: DlpPolicyDto, ...commonErrors },
      summary: "Remove a DLP policy (settings:manage)",
    },

    // --- Settings: cost centers + chargeback -------------------------------
    listCostCenters: {
      method: "GET",
      path: "/v1/settings/cost-centers",
      responses: { 200: page(CostCenterDto), ...commonErrors },
      summary: "This workspace's cost-center hierarchy (with seat counts)",
    },
    createCostCenter: {
      method: "POST",
      path: "/v1/settings/cost-centers",
      body: CreateCostCenterBody,
      responses: { 201: CostCenterDto, ...commonErrors },
      summary: "Add a cost center (settings:manage)",
    },
    updateCostCenter: {
      method: "PUT",
      path: "/v1/settings/cost-centers/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdateCostCenterBody,
      responses: { 200: CostCenterDto, ...commonErrors },
      summary: "Edit a cost center (settings:manage; optimistic)",
    },
    deleteCostCenter: {
      method: "POST",
      path: "/v1/settings/cost-centers/:id/delete",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: CostCenterDto, ...commonErrors },
      summary: "Remove a cost center (settings:manage; must have no children)",
    },
    listCostCenterAssignments: {
      method: "GET",
      path: "/v1/settings/cost-centers/assignments",
      responses: { 200: page(CostCenterAssignmentDto), ...commonErrors },
      summary: "Tenant members and their cost-center assignment",
    },
    assignCostCenter: {
      method: "POST",
      path: "/v1/settings/cost-centers/assign",
      body: AssignCostCenterBody,
      responses: { 200: CostCenterAssignmentDto, ...commonErrors },
      summary: "Assign a member to a cost center (settings:manage)",
    },
    getChargebackSettings: {
      method: "GET",
      path: "/v1/settings/chargeback",
      responses: { 200: ChargebackSettingsDto, ...commonErrors },
      summary: "This workspace's chargeback allocation settings (defaults-merged)",
    },
    updateChargebackSettings: {
      method: "PUT",
      path: "/v1/settings/chargeback",
      body: UpdateChargebackSettingsBody,
      responses: { 200: ChargebackSettingsDto, ...commonErrors },
      summary: "Save chargeback allocation settings (settings:manage; optimistic)",
    },
    getChargebackReport: {
      method: "GET",
      path: "/v1/settings/chargeback/report",
      responses: { 200: ChargebackReportDto, ...commonErrors },
      summary: "The current-month chargeback, allocated across cost centers (conserved)",
    },

    // --- Suppliers (FEATURES §11.1) ----------------------------------------
    listSuppliers: {
      method: "GET",
      path: "/v1/suppliers",
      query: PageQuery.extend({
        status: SupplierStatus.optional(),
        riskTier: RiskLevel.optional(),
        tier: z.coerce.number().int().optional(),
        category: z.string().optional(),
        country: z.string().optional(),
        flag: z.string().optional(),
        q: z.string().optional(),
      }),
      responses: { 200: page(SupplierDto), ...commonErrors },
      summary: "List suppliers (cursor-paginated; filter by tier/risk/category/country/flag/search)",
    },
    getSupplier: {
      method: "GET",
      path: "/v1/suppliers/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: SupplierDto, ...commonErrors },
      summary: "Fetch one supplier (with scorecard + profile)",
    },
    createSupplier: {
      method: "POST",
      path: "/v1/suppliers",
      body: CreateSupplierBody,
      responses: { 201: SupplierDto, ...commonErrors },
      summary: "Create a supplier",
    },
    updateSupplier: {
      method: "POST",
      path: "/v1/suppliers/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdateSupplierBody,
      responses: { 200: SupplierDto, ...commonErrors },
      summary: "Update a supplier (optimistic concurrency via version)",
    },
    scorecardSuppliers: {
      method: "GET",
      path: "/v1/supplier-scorecard",
      query: ScorecardWeightsQuery,
      responses: { 200: page(SupplierDto), ...commonErrors },
      summary: "Suppliers ranked by weighted score (PPM/OTD/OQE/SCAR weights as query params)",
    },

    // --- PPAP submissions (FEATURES §11.2) ---------------------------------
    listPpap: {
      method: "GET",
      path: "/v1/ppap",
      query: PageQuery.extend({
        supplierId: z.string().uuid().optional(),
        status: PpapStatus.optional(),
        customer: z.string().optional(),
        level: z.coerce.number().int().optional(),
        q: z.string().optional(),
      }),
      responses: { 200: page(PpapSubmissionDto), ...commonErrors },
      summary: "List PPAP submissions (cursor-paginated; filter by supplier/status/customer/level/search)",
    },
    getPpap: {
      method: "GET",
      path: "/v1/ppap/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: PpapSubmissionDto, ...commonErrors },
      summary: "Fetch one PPAP submission (with its 18 elements + completeness)",
    },
    createPpap: {
      method: "POST",
      path: "/v1/ppap",
      body: CreatePpapBody,
      responses: { 201: PpapSubmissionDto, ...commonErrors },
      summary: "Open a PPAP submission (auto-seeds the 18 elements as pending)",
    },
    updatePpap: {
      method: "POST",
      path: "/v1/ppap/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdatePpapBody,
      responses: { 200: PpapSubmissionDto, ...commonErrors },
      summary: "Update a PPAP submission (optimistic concurrency via version)",
    },
    updatePpapElement: {
      method: "POST",
      path: "/v1/ppap/:id/elements/:no",
      pathParams: z.object({ id: z.string().uuid(), no: z.coerce.number().int().min(1).max(18) }),
      body: UpdatePpapElementBody,
      responses: { 200: PpapSubmissionDto, ...commonErrors },
      summary: "Set one element's status / reviewer / comment (optimistic via version)",
    },
    decidePpap: {
      method: "POST",
      path: "/v1/ppap/:id/decision",
      pathParams: z.object({ id: z.string().uuid() }),
      body: PpapDecisionBody,
      responses: { 200: PpapSubmissionDto, ...commonErrors },
      summary: "Overall approve/reject (approve blocked until every non-N/A element is approved)",
    },

    // --- SCAR & chargebacks (FEATURES §11.3) -------------------------------
    listScars: {
      method: "GET",
      path: "/v1/scars",
      query: PageQuery.extend({
        supplierId: z.string().uuid().optional(),
        status: ScarStatus.optional(),
        severity: ScarSeverity.optional(),
        overdue: z.coerce.boolean().optional(),
        q: z.string().optional(),
      }),
      responses: { 200: page(ScarDto), ...commonErrors },
      summary: "List SCARs (cursor-paginated; filter by supplier/status/severity/overdue/search)",
    },
    getScar: {
      method: "GET",
      path: "/v1/scars/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: ScarDto, ...commonErrors },
      summary: "Fetch one SCAR",
    },
    createScar: {
      method: "POST",
      path: "/v1/scars",
      body: CreateScarBody,
      responses: { 201: ScarDto, ...commonErrors },
      summary: "Raise a SCAR against a supplier (auto-codes SCAR-YYYY-NNNN)",
    },
    updateScar: {
      method: "POST",
      path: "/v1/scars/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdateScarBody,
      responses: { 200: ScarDto, ...commonErrors },
      summary: "Update a SCAR (optimistic concurrency via version)",
    },
    advanceScar: {
      method: "POST",
      path: "/v1/scars/:id/advance",
      pathParams: z.object({ id: z.string().uuid() }),
      body: AdvanceScarBody,
      responses: { 200: ScarDto, ...commonErrors },
      summary: "Advance the 8D one discipline forward (blocked past D8)",
    },
    acknowledgeScar: {
      method: "POST",
      path: "/v1/scars/:id/acknowledge",
      pathParams: z.object({ id: z.string().uuid() }),
      body: AcknowledgeScarBody,
      responses: { 200: ScarDto, ...commonErrors },
      summary: "Record the supplier's acknowledgement of the SCAR",
    },
    chargebackScar: {
      method: "POST",
      path: "/v1/scars/:id/chargeback",
      pathParams: z.object({ id: z.string().uuid() }),
      body: ScarChargebackBody,
      responses: { 200: ScarDto, ...commonErrors },
      summary: "Set / transition the chargeback (one-way: none→pending→debit_issued→closed)",
    },
    assignScar: {
      method: "POST",
      path: "/v1/scars/:id/assign",
      pathParams: z.object({ id: z.string().uuid() }),
      body: AssignScarBody,
      responses: { 200: ScarDto, ...commonErrors },
      summary: "Assign, reassign, or clear a SCAR's owner (audited)",
    },

    // --- Supplier portal (external, read-only; FEATURES §17) ---------------
    // Partner-only (`portal:view`), and every response is additionally scoped to
    // the caller's own supplier — a foreign id is 404, never 403.
    getPortalIdentity: {
      method: "GET",
      path: "/v1/portal/me",
      responses: { 200: PortalIdentityDto, ...commonErrors },
      summary: "The partner's own supplier identity",
    },
    listPortalScars: {
      method: "GET",
      path: "/v1/portal/scars",
      query: PageQuery,
      responses: { 200: page(PortalScarDto), ...commonErrors },
      summary: "The partner's own SCARs (cursor-paginated, scoped to their supplier)",
    },
    getPortalScar: {
      method: "GET",
      path: "/v1/portal/scars/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: PortalScarDto, ...commonErrors },
      summary: "One of the partner's own SCARs (foreign supplier → 404)",
    },
    listPortalPpap: {
      method: "GET",
      path: "/v1/portal/ppap",
      query: PageQuery,
      responses: { 200: page(PortalPpapDto), ...commonErrors },
      summary: "The partner's own PPAP submissions (cursor-paginated, scoped)",
    },
    getPortalPpap: {
      method: "GET",
      path: "/v1/portal/ppap/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: PortalPpapDto, ...commonErrors },
      summary: "One of the partner's own PPAP submissions (foreign supplier → 404)",
    },
    respondPortalScar: {
      method: "POST",
      path: "/v1/portal/scars/:id/respond",
      pathParams: z.object({ id: z.string().uuid() }),
      body: PortalScarRespondBody,
      responses: { 200: PortalScarDto, ...commonErrors },
      summary: "Supplier responds to a SCAR (note + optional acknowledge; audited actor_kind=partner)",
    },
    resubmitPortalPpap: {
      method: "POST",
      path: "/v1/portal/ppap/:id/resubmit",
      pathParams: z.object({ id: z.string().uuid() }),
      body: PortalPpapResubmitBody,
      responses: { 200: PortalPpapDto, ...commonErrors },
      summary: "Supplier re-submits a PPAP package after feedback (audited actor_kind=partner)",
    },
    // Evidence upload (P11): a partner-scoped mirror of the internal presign flow.
    // The file is created UNLINKED and owned by the caller; it is attached to one
    // of the partner's own records only via respond/re-submit `fileIds`, so a
    // partner never reaches the internal `/v1/files/*` routes or names an entity.
    presignPortalEvidence: {
      method: "POST",
      path: "/v1/portal/files/presign",
      body: PortalEvidencePresignBody,
      responses: { 201: PresignFileResult, ...commonErrors },
      summary: "Presign a portal evidence upload (partner-scoped; file created unlinked)",
    },
    completePortalEvidence: {
      method: "POST",
      path: "/v1/portal/files/:id/complete",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: FileDto, ...commonErrors },
      summary: "Finalise a portal evidence upload and hand it to the AV scan",
    },

    // --- Notifications -----------------------------------------------------
    listNotifications: {
      method: "GET",
      path: "/v1/notifications",
      query: PageQuery.extend({
        unread: z.coerce.boolean().optional(),
        starred: z.coerce.boolean().optional(),
        entityKind: z.string().max(40).optional(),
      }),
      responses: { 200: page(NotificationDto), ...commonErrors },
      summary: "List the current user's notifications (cursor-paginated; unread/starred/type filters)",
    },
    unreadCount: {
      method: "GET",
      path: "/v1/notifications/unread-count",
      responses: { 200: UnreadCountDto, ...commonErrors },
      summary: "The current user's unread notification count (the bell badge)",
    },
    markNotificationRead: {
      method: "POST",
      path: "/v1/notifications/:id/read",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: NotificationDto, ...commonErrors },
      summary: "Mark one of the current user's notifications read",
    },
    markAllNotificationsRead: {
      method: "POST",
      path: "/v1/notifications/read-all",
      body: z.object({}),
      responses: { 200: CountDto, ...commonErrors },
      summary: "Mark all of the current user's notifications read",
    },
    starNotification: {
      method: "POST",
      path: "/v1/notifications/:id/star",
      pathParams: z.object({ id: z.string().uuid() }),
      body: StarNotificationBody,
      responses: { 200: NotificationDto, ...commonErrors },
      summary: "Star or un-star one of the current user's notifications",
    },
    dismissNotification: {
      method: "POST",
      path: "/v1/notifications/:id/dismiss",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: CountDto, ...commonErrors },
      summary: "Dismiss (soft-delete) one of the current user's notifications",
    },
    getNotificationPrefs: {
      method: "GET",
      path: "/v1/notification-prefs",
      responses: { 200: NotificationPrefsDto, ...commonErrors },
      summary: "The current user's per-kind channel preferences",
    },
    updateNotificationPrefs: {
      method: "PUT",
      path: "/v1/notification-prefs",
      body: UpdateNotificationPrefsBody,
      responses: { 200: NotificationPrefsDto, ...commonErrors },
      summary: "Replace the current user's notification channel matrix",
    },

    // --- Files -------------------------------------------------------------
    presignFile: {
      method: "POST",
      path: "/v1/files/presign",
      body: PresignFileBody,
      responses: { 201: PresignFileResult, ...commonErrors },
      summary: "Validate mime + size and get a presigned upload URL (file row: pending)",
    },
    completeFile: {
      method: "POST",
      path: "/v1/files/:id/complete",
      pathParams: z.object({ id: z.string().uuid() }),
      body: CompleteFileBody,
      responses: { 200: FileDto, ...commonErrors },
      summary: "Confirm the upload finished; server verifies the object and records its hash",
    },
    getFile: {
      method: "GET",
      path: "/v1/files/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: FileDto, ...commonErrors },
      summary: "Fetch a file's metadata",
    },
    downloadFile: {
      method: "GET",
      path: "/v1/files/:id/download",
      pathParams: z.object({ id: z.string().uuid() }),
      query: DownloadFileQuery,
      responses: { 200: DownloadFileResult, ...commonErrors },
      summary: "Get a presigned download URL (inline for preview / attachment; gated on AV scan; audited)",
    },
  },
  {
    strictStatusCodes: true,
  },
);

export type Contract = typeof contract;
