import { initContract } from "@ts-rest/core";
import { z } from "zod";
import {
  AcceptAiSummaryBody,
  AdvanceAuditBody,
  AdvanceCapaBody,
  AiDraftDto,
  AiDraftRequest,
  AiSummaryDto,
  AssignCapaBody,
  AssignEightDBody,
  AssignInspectionBody,
  AssignNcrBody,
  AssignScarBody,
  AuditDto,
  AuditFindingDto,
  AuditFrequencyResult,
  AuditStatsDto,
  UpdateAuditChecklistItemBody,
  CapaActionDto,
  CapaDto,
  CreateAuditBody,
  CreateAuditFindingBody,
  CompleteFileBody,
  CompleteInspectionBody,
  CreateCapaActionBody,
  CreateCapaBody,
  CreateDocumentBody,
  CreateFindingBody,
  CreateInspectionBody,
  CreateNcrActionBody,
  CreateNcrBody,
  CreateTemplateBody,
  UpdateTemplateBody,
  TemplateVersionBody,
  CreateEightDBody,
  CreateExportBody,
  DocumentDto,
  DocumentVersionDto,
  DownloadFileQuery,
  DownloadFileResult,
  EightDDto,
  ExportDto,
  FileDto,
  FindingDto,
  InspectionDto,
  MeDto,
  DashboardDto,
  WorkspacesDto,
  WorkspaceDto,
  SwitchWorkspaceBody,
  MemberDto,
  PlantDto,
  AreaDto,
  MemberWorkloadList,
  NcrActionDto,
  NcrDto,
  SyncQuery,
  NcrSyncDelta,
  InspectionSyncDelta,
  SyncHealthBody,
  CountDto,
  NewDocumentVersionBody,
  NotificationDto,
  NotificationPageDto,
  NotificationPrefsDto,
  UpdateUserPreferencesBody,
  UserPreferencesDto,
  StarNotificationBody,
  PresignFileBody,
  PresignFileResult,
  AuditEventDto,
  AuditLogEntryDto,
  AuditLogQuery,
  CommentDto,
  CreateCommentBody,
  CreateEntityLinkBody,
  EntityLinkDto,
  EntityRefQuery,
  RaiseCapaFromFindingBody,
  RaiseNcrFromFindingBody,
  ReviewDocumentBody,
  SearchResults,
  UnreadCountDto,
  UpdateEightDStepBody,
  UpdateNotificationPrefsBody,
  RevertCapaBody,
  ScorecardWeightsQuery,
  SetRecurrenceBody,
  StartInspectionBody,
  SupplierDto,
  CreateSupplierBody,
  UpdateSupplierBody,
  PpapSubmissionDto,
  CreatePpapBody,
  UpdatePpapBody,
  RiskPredictionDto,
  PredictionDetailResponse,
  UpdatePpapElementBody,
  PpapDecisionBody,
  ScarDto,
  CreateScarBody,
  UpdateScarBody,
  AdvanceScarBody,
  AcknowledgeScarBody,
  ScarChargebackBody,
  PortalIdentityDto,
  PortalScarDto,
  PortalPpapDto,
  PortalScarRespondBody,
  PortalPpapResubmitBody,
  PortalEvidencePresignBody,
  BrandingDto,
  UpdateBrandingBody,
  SessionPolicyDto,
  UpdateSessionPolicyBody,
  NcrValidationRuleDto,
  CreateNcrValidationRuleBody,
  UpdateNcrValidationRuleBody,
  LegalHoldDto,
  CreateLegalHoldBody,
  UpdateLegalHoldBody,
  DlpPolicyDto,
  CreateDlpPolicyBody,
  UpdateDlpPolicyBody,
  CostCenterDto,
  CreateCostCenterBody,
  UpdateCostCenterBody,
  CostCenterAssignmentDto,
  AssignCostCenterBody,
  ChargebackSettingsDto,
  UpdateChargebackSettingsBody,
  ChargebackReportDto,
  FmeaDto,
  CreateFmeaBody,
  UpdateFmeaBody,
  FmeaItemDto,
  CreateFmeaItemBody,
  UpdateFmeaItemBody,
  RiskDto,
  RiskListQuery,
  InstrumentDto,
  InstrumentListQuery,
  InstrumentSummaryDto,
  CreateInstrumentBody,
  UpdateInstrumentBody,
  RetireInstrumentBody,
  CalibrationEventDto,
  CalibrationEventListQuery,
  CreateCalibrationEventBody,
  AttachCertificateBody,
  RaiseNcrFromCalibrationBody,
  CompetencyDto,
  CompetencyListQuery,
  CreateCompetencyBody,
  UpdateCompetencyBody,
  ArchiveCompetencyBody,
  UnarchiveCompetencyBody,
  ReorderCompetenciesBody,
  ReorderCompetenciesResult,
  TrainingRecordDto,
  CreateTrainingRecordBody,
  CreateTrainingRecordResult,
  TrainingMatrixRowDto,
  TrainingMatrixQuery,
  TrainingSummaryDto,
  TrainingGapDto,
  TrainingGapsQuery,
  TrainingRecordsQuery,
  CreateRiskBody,
  UpdateRiskBody,
  RiskSummaryDto,
  MsaStudyDto,
  MsaListQuery,
  CreateMsaStudyBody,
  MsaCompleteBody,
  MsaReopenBody,
  MsaMeasurementBatchBody,
  MsaAnalysisResult,
  TemplateDto,
  TransitionDocumentBody,
  TransitionEightDBody,
  TransitionNcrBody,
  UpdateCapaActionStatusBody,
  UpdateNcrActionStatusBody,
  VerifyNcrBody,
  ComplaintDto,
  ComplaintListQuery,
  CreateComplaintBody,
  UpdateComplaintBody,
  AcknowledgeComplaintBody,
  CloseComplaintBody,
  ComplaintConvertBody,
  ComplaintConvertResult,
  ComplaintSummaryDto,
  EcnDto,
  EcnListQuery,
  CreateEcnBody,
  UpdateEcnBody,
  EcnSummaryDto,
  EcnApprovalDto,
  DecideEcnApprovalBody,
  EcnLifecycleBody,
  EcnLinkBody,
  EcnLinkDto,
} from "./dto.js";
import { ErrorBody, PageQuery, page } from "./http.js";
import {
  AuditPhase,
  AuditType,
  CapaPhase,
  CapaType,
  EcnApprovalStage,
  DocumentCategory,
  DocumentStatus,
  EightDStatus,
  EntityKind,
  ExportResource,
  ExportStatus,
  InspectionStatus,
  NcrPriority,
  NcrStatus,
  PpapStatus,
  ScarSeverity,
  ScarStatus,
  RiskLevel,
  SupplierStatus,
  TemplateStatus,
  PredictionSubjectKind,
} from "./enums.js";
import {
  Query,
  QuerySourcesResult,
  QueryRowsResult,
  QueryMetricResult,
  QuerySeriesResult,
} from "./query.js";
import { ReportDefinitionDto, CreateReportBody, UpdateReportBody } from "./report.js";
import {
  IntegrationDto,
  IntegrationEventDto,
  ConnectorSchemaResult,
  CreateIntegrationBody,
  UpdateIntegrationBody,
  ConnectIntegrationBody,
  WebhookTestResultDto,
} from "./integration.js";
import { ConfigureWebhookBody, ConfigureWebhookResult, WebhookPolicyDto } from "./webhook-config.js";
import {
  ImportTargetsResult,
  ImportProfileDto,
  ImportRunDto,
  CreateImportProfileBody,
  CreateImportRunBody,
  CommitImportRunBody,
} from "./import.js";
import {
  SpcCharacteristicsResult,
  SpcChartDto,
  IngestMeasurementsBody,
} from "./spc.js";
import { GraphExpandResult, GraphQueryId, GraphQueryResult, GraphSeedsResult } from "./graph.js";

/**
 * The API contract (03 §1) — contract-first, in `packages/types` so it is the
 * one artifact the server, the OpenAPI document, and the typed client all
 * derive from. The Nest handlers validate their inputs against these very
 * schemas; the web client is `initClient(contract)`. Neither side can drift
 * from the other because there is only one definition.
 */

const c = initContract();

/** Errors any authenticated route may return. Declared once, spread per route. */
const commonErrors = {
  400: ErrorBody,
  401: ErrorBody,
  403: ErrorBody,
  404: ErrorBody,
  409: ErrorBody,
  422: ErrorBody,
  429: ErrorBody,
} as const;

export const contract = c.router(
  {
    getMe: {
      method: "GET",
      path: "/v1/me",
      responses: { 200: MeDto, 401: ErrorBody },
      summary: "The current session's identity and capabilities",
    },
    getDashboard: {
      method: "GET",
      path: "/v1/me/dashboard",
      responses: { 200: DashboardDto, ...commonErrors },
      summary: "The role-aware home dashboard (KPIs + queues) for the caller",
    },
    myWorkspaces: {
      method: "GET",
      path: "/v1/me/workspaces",
      responses: { 200: WorkspacesDto, ...commonErrors },
      summary: "Every workspace the signed-in person belongs to (the switcher)",
    },
    switchWorkspace: {
      method: "POST",
      path: "/v1/me/switch-workspace",
      body: SwitchWorkspaceBody,
      responses: { 200: WorkspaceDto, ...commonErrors },
      summary: "Switch the active workspace (mints a session in the target tenant)",
    },

    // --- Members directory -------------------------------------------------
    listMembers: {
      method: "GET",
      path: "/v1/members",
      query: PageQuery,
      responses: { 200: page(MemberDto), ...commonErrors },
      summary: "List this tenant's members (id → name + role) so the UI can resolve people",
    },
    listPlants: {
      method: "GET",
      path: "/v1/plants",
      responses: { 200: z.object({ items: z.array(PlantDto) }), ...commonErrors },
      summary: "Sites the caller may raise records in (plant-scoped by role) — the CreateWizard Site select",
    },
    listAreas: {
      method: "GET",
      path: "/v1/areas",
      query: z.object({ plantId: z.string().uuid().optional() }),
      responses: { 200: z.object({ items: z.array(AreaDto) }), ...commonErrors },
      summary:
        "Areas within the caller's visible plants (Sprint 05 C1/C6) — the instrument register's plant→area cascading select and area-name display; `plantId` narrows to one plant, omitted returns every area in the caller's plant scope",
    },
    listMemberWorkload: {
      method: "GET",
      path: "/v1/members/workload",
      responses: { 200: MemberWorkloadList, ...commonErrors },
      summary: "Members with a live workload signal (open assigned NCRs) — the assign sheet",
    },

    // --- Search ------------------------------------------------------------
    search: {
      method: "GET",
      path: "/v1/search",
      query: z.object({ q: z.string().min(1).max(200) }),
      responses: { 200: SearchResults, ...commonErrors },
      summary: "Federated full-text search across records (top 6 per kind), plant-scoped by role",
    },

    // --- Inspection templates ---------------------------------------------
    listTemplates: {
      method: "GET",
      path: "/v1/inspection-templates",
      query: PageQuery.extend({ status: TemplateStatus.optional() }),
      responses: { 200: page(TemplateDto), ...commonErrors },
      summary: "List inspection templates (cursor-paginated)",
    },
    createTemplate: {
      method: "POST",
      path: "/v1/inspection-templates",
      body: CreateTemplateBody,
      responses: { 201: TemplateDto, ...commonErrors },
      summary: "Create a draft template",
    },
    getTemplate: {
      method: "GET",
      path: "/v1/inspection-templates/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: TemplateDto, ...commonErrors },
      summary: "Fetch one template (with its form schema)",
    },
    updateTemplate: {
      method: "PUT",
      path: "/v1/inspection-templates/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdateTemplateBody,
      responses: { 200: TemplateDto, ...commonErrors },
      summary: "Edit a draft template's name + schema (optimistic; drafts only)",
    },
    versionTemplate: {
      method: "POST",
      path: "/v1/inspection-templates/:id/version",
      pathParams: z.object({ id: z.string().uuid() }),
      body: CreateTemplateBody,
      responses: { 201: TemplateDto, ...commonErrors },
      summary: "Create the next-version draft of a template (same lineage)",
    },
    publishTemplate: {
      method: "POST",
      path: "/v1/inspection-templates/:id/publish",
      pathParams: z.object({ id: z.string().uuid() }),
      body: TemplateVersionBody,
      responses: { 200: TemplateDto, ...commonErrors },
      summary: "Publish a draft template (makes its schema immutable)",
    },
    archiveTemplate: {
      method: "POST",
      path: "/v1/inspection-templates/:id/archive",
      pathParams: z.object({ id: z.string().uuid() }),
      body: TemplateVersionBody,
      responses: { 200: TemplateDto, ...commonErrors },
      summary: "Archive a template (a superseded version drops out of the list)",
    },

    // --- Inspections -------------------------------------------------------
    listInspections: {
      method: "GET",
      path: "/v1/inspections",
      query: PageQuery.extend({
        status: InspectionStatus.optional(),
        plantId: z.string().uuid().optional(),
      }),
      responses: { 200: page(InspectionDto), ...commonErrors },
      summary: "List inspections (cursor-paginated, plant-scoped by role)",
    },
    createInspection: {
      method: "POST",
      path: "/v1/inspections",
      body: CreateInspectionBody,
      responses: { 201: InspectionDto, ...commonErrors },
      summary: "Schedule an inspection from a published template",
    },
    getInspection: {
      method: "GET",
      path: "/v1/inspections/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: InspectionDto, ...commonErrors },
      summary: "Fetch one inspection",
    },
    startInspection: {
      method: "POST",
      path: "/v1/inspections/:id/start",
      pathParams: z.object({ id: z.string().uuid() }),
      body: StartInspectionBody,
      responses: { 200: InspectionDto, ...commonErrors },
      summary: "Begin an inspection (scheduled → in_progress)",
    },
    completeInspection: {
      method: "POST",
      path: "/v1/inspections/:id/complete",
      pathParams: z.object({ id: z.string().uuid() }),
      body: CompleteInspectionBody,
      responses: { 200: InspectionDto, ...commonErrors },
      summary: "Submit responses, validate + score, and complete an inspection",
    },
    setInspectionRecurrence: {
      method: "PUT",
      path: "/v1/inspections/:id/recurrence",
      pathParams: z.object({ id: z.string().uuid() }),
      body: SetRecurrenceBody,
      responses: { 200: InspectionDto, ...commonErrors },
      summary: "Set, change, or clear a series head's recurrence (06 materialises occurrences)",
    },
    assignInspection: {
      method: "POST",
      path: "/v1/inspections/:id/assign",
      pathParams: z.object({ id: z.string().uuid() }),
      body: AssignInspectionBody,
      responses: { 200: InspectionDto, ...commonErrors },
      summary: "Assign, reassign, or clear an inspection's inspector (audited)",
    },
    listInspectionOccurrences: {
      method: "GET",
      path: "/v1/inspections/:id/occurrences",
      pathParams: z.object({ id: z.string().uuid() }),
      query: PageQuery,
      responses: { 200: page(InspectionDto), ...commonErrors },
      summary: "List a recurring series' materialised occurrences",
    },

    // --- Findings ----------------------------------------------------------
    listFindings: {
      method: "GET",
      path: "/v1/inspections/:id/findings",
      pathParams: z.object({ id: z.string().uuid() }),
      query: PageQuery,
      responses: { 200: page(FindingDto), ...commonErrors },
      summary: "List an inspection's findings",
    },
    createFinding: {
      method: "POST",
      path: "/v1/inspections/:id/findings",
      pathParams: z.object({ id: z.string().uuid() }),
      body: CreateFindingBody,
      responses: { 201: FindingDto, ...commonErrors },
      summary: "Record a finding against an inspection",
    },

    // --- NCRs --------------------------------------------------------------
    listNcrs: {
      method: "GET",
      path: "/v1/ncrs",
      query: PageQuery.extend({
        status: NcrStatus.optional(),
        priority: NcrPriority.optional(),
        plantId: z.string().uuid().optional(),
      }),
      responses: { 200: page(NcrDto), ...commonErrors },
      summary: "List NCRs (cursor-paginated, plant-scoped by role)",
    },
    syncNcr: {
      method: "GET",
      path: "/v1/sync/ncr",
      query: SyncQuery,
      responses: { 200: NcrSyncDelta, ...commonErrors },
      summary: "Delta pull for the mobile offline mirror — NCRs changed since a cursor, plus tombstones",
    },
    syncInspections: {
      method: "GET",
      path: "/v1/sync/inspections",
      query: SyncQuery,
      responses: { 200: InspectionSyncDelta, ...commonErrors },
      summary: "Delta pull for the mobile offline mirror — inspections changed since a cursor, plus tombstones",
    },
    reportSyncHealth: {
      method: "POST",
      path: "/v1/sync/health",
      body: SyncHealthBody,
      responses: { 200: z.object({ ok: z.boolean() }), ...commonErrors },
      summary: "A device reports its offline-sync health (feeds the admin 'Failed syncs' tile)",
    },
    createNcr: {
      method: "POST",
      path: "/v1/ncrs",
      body: CreateNcrBody,
      responses: { 201: NcrDto, ...commonErrors },
      summary: "Raise an NCR (optionally from a finding)",
    },
    getNcr: {
      method: "GET",
      path: "/v1/ncrs/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: NcrDto, ...commonErrors },
      summary: "Fetch one NCR",
    },
    transitionNcr: {
      method: "POST",
      path: "/v1/ncrs/:id/transition",
      pathParams: z.object({ id: z.string().uuid() }),
      body: TransitionNcrBody,
      responses: { 200: NcrDto, ...commonErrors },
      summary: "Advance an NCR through its lifecycle (assign, start, resolve, close, escalate, reopen)",
    },
    verifyNcr: {
      method: "POST",
      path: "/v1/ncrs/:id/verify",
      pathParams: z.object({ id: z.string().uuid() }),
      body: VerifyNcrBody,
      responses: { 200: NcrDto, ...commonErrors },
      summary: "Verify a resolved NCR (four-eyes: not the resolver)",
    },
    assignNcr: {
      method: "POST",
      path: "/v1/ncrs/:id/assign",
      pathParams: z.object({ id: z.string().uuid() }),
      body: AssignNcrBody,
      responses: { 200: NcrDto, ...commonErrors },
      summary: "Assign, reassign, or clear an NCR's owner (audited)",
    },

    // --- NCR corrective actions -------------------------------------------
    listNcrActions: {
      method: "GET",
      path: "/v1/ncrs/:id/actions",
      pathParams: z.object({ id: z.string().uuid() }),
      query: PageQuery,
      responses: { 200: page(NcrActionDto), ...commonErrors },
      summary: "List an NCR's corrective/preventive actions",
    },
    createNcrAction: {
      method: "POST",
      path: "/v1/ncrs/:id/actions",
      pathParams: z.object({ id: z.string().uuid() }),
      body: CreateNcrActionBody,
      responses: { 201: NcrActionDto, ...commonErrors },
      summary: "Add a corrective/preventive/containment action to an NCR",
    },
    updateNcrActionStatus: {
      method: "POST",
      path: "/v1/ncr-actions/:id/status",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdateNcrActionStatusBody,
      responses: { 200: NcrActionDto, ...commonErrors },
      summary: "Advance an action's status (pending → in_progress → done → verified)",
    },

    // --- 8D ----------------------------------------------------------------
    listEightDs: {
      method: "GET",
      path: "/v1/eight-ds",
      query: PageQuery.extend({
        status: EightDStatus.optional(),
        ncrId: z.string().uuid().optional(),
      }),
      responses: { 200: page(EightDDto), ...commonErrors },
      summary: "List 8D reports (cursor-paginated)",
    },
    createEightD: {
      method: "POST",
      path: "/v1/eight-ds",
      body: CreateEightDBody,
      responses: { 201: EightDDto, ...commonErrors },
      summary: "Open an 8D (optionally from an NCR, which it then blocks from closing)",
    },
    getEightD: {
      method: "GET",
      path: "/v1/eight-ds/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: EightDDto, ...commonErrors },
      summary: "Fetch one 8D with its disciplines",
    },
    updateEightDStep: {
      method: "POST",
      path: "/v1/eight-ds/:id/steps/:step",
      pathParams: z.object({ id: z.string().uuid(), step: z.coerce.number().int().min(1).max(8) }),
      body: UpdateEightDStepBody,
      responses: { 200: EightDDto, ...commonErrors },
      summary: "Update a discipline (D1–D8); completing one is gated by its prerequisites",
    },
    transitionEightD: {
      method: "POST",
      path: "/v1/eight-ds/:id/transition",
      pathParams: z.object({ id: z.string().uuid() }),
      body: TransitionEightDBody,
      responses: { 200: EightDDto, ...commonErrors },
      summary: "Complete (all disciplines done) or cancel an 8D",
    },
    assignEightD: {
      method: "POST",
      path: "/v1/eight-ds/:id/assign",
      pathParams: z.object({ id: z.string().uuid() }),
      body: AssignEightDBody,
      responses: { 200: EightDDto, ...commonErrors },
      summary: "Assign, reassign, or clear an 8D's team lead and/or champion (audited)",
    },

    // --- Audits ------------------------------------------------------------
    listAudits: {
      method: "GET",
      path: "/v1/audits",
      query: PageQuery.extend({
        status: z.union([AuditPhase, z.enum(["active", "completed"])]).optional(),
        type: AuditType.optional(),
        plantId: z.string().uuid().optional(),
        /** Free-text title/code filter — distinct from federated `/v1/search`. */
        q: z.string().min(1).max(200).optional(),
        /** Caller is lead auditor, in `team`, or in `auditeeIds`. */
        mine: z.coerce.boolean().optional(),
        /** Audits whose [startAt, endAt] overlaps this window (schedule view). */
        from: z.string().datetime().optional(),
        to: z.string().datetime().optional(),
      }),
      responses: { 200: page(AuditDto), ...commonErrors },
      summary: "List audits (cursor-paginated, plant-scoped by role)",
    },
    getAuditFrequency: {
      method: "GET",
      path: "/v1/audits/frequency",
      responses: { 200: AuditFrequencyResult, ...commonErrors },
      summary: "Last-6-months audit counts grouped by type",
    },
    getAuditStats: {
      method: "GET",
      path: "/v1/audits/stats",
      responses: { 200: AuditStatsDto, ...commonErrors },
      summary: "KPI strip: active / planned-next-90d / completed-YTD / open-findings",
    },
    createAudit: {
      method: "POST",
      path: "/v1/audits",
      body: CreateAuditBody,
      responses: { 201: AuditDto, ...commonErrors },
      summary: "Schedule an audit",
    },
    getAudit: {
      method: "GET",
      path: "/v1/audits/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: AuditDto, ...commonErrors },
      summary: "Fetch one audit",
    },
    advanceAudit: {
      method: "POST",
      path: "/v1/audits/:id/advance",
      pathParams: z.object({ id: z.string().uuid() }),
      body: AdvanceAuditBody,
      responses: { 200: AuditDto, ...commonErrors },
      summary: "Advance an audit one phase forward",
    },
    updateAuditChecklistItem: {
      method: "PATCH",
      path: "/v1/audits/:id/checklist/:itemId",
      pathParams: z.object({ id: z.string().uuid(), itemId: z.string().uuid() }),
      body: UpdateAuditChecklistItemBody,
      responses: { 200: AuditDto, ...commonErrors },
      summary: "Score one checklist clause; auto-links a finding on a first NC/opportunity",
    },
    listAuditFindings: {
      method: "GET",
      path: "/v1/audits/:id/findings",
      pathParams: z.object({ id: z.string().uuid() }),
      query: PageQuery,
      responses: { 200: page(AuditFindingDto), ...commonErrors },
      summary: "List an audit's findings",
    },
    createAuditFinding: {
      method: "POST",
      path: "/v1/audits/:id/findings",
      pathParams: z.object({ id: z.string().uuid() }),
      body: CreateAuditFindingBody,
      responses: { 201: AuditFindingDto, ...commonErrors },
      summary: "Record a finding against an audit",
    },
    raiseNcrFromAuditFinding: {
      method: "POST",
      path: "/v1/audit-findings/:id/raise-ncr",
      pathParams: z.object({ id: z.string().uuid() }),
      body: RaiseNcrFromFindingBody,
      responses: { 201: NcrDto, ...commonErrors },
      summary: "Raise an NCR from an audit finding (links the finding)",
    },
    raiseCapaFromAuditFinding: {
      method: "POST",
      path: "/v1/audit-findings/:id/raise-capa",
      pathParams: z.object({ id: z.string().uuid() }),
      body: RaiseCapaFromFindingBody,
      responses: { 201: CapaDto, ...commonErrors },
      summary: "Raise a CAPA from an audit finding (links the finding)",
    },

    // --- Exports -----------------------------------------------------------
    listExports: {
      method: "GET",
      path: "/v1/exports",
      query: PageQuery.extend({
        resource: ExportResource.optional(),
        status: ExportStatus.optional(),
      }),
      responses: { 200: page(ExportDto), ...commonErrors },
      summary: "List exports (cursor-paginated, newest first)",
    },
    createExport: {
      method: "POST",
      path: "/v1/exports",
      body: CreateExportBody,
      // 202: the render runs on the `reports` queue; poll getExport for the URL.
      responses: { 202: ExportDto, ...commonErrors },
      summary: "Request an async export (returns 202; poll for the download URL)",
    },
    getExport: {
      method: "GET",
      path: "/v1/exports/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: ExportDto, ...commonErrors },
      summary: "Fetch an export's status (with a presigned URL once completed)",
    },

    // --- Predictive risk (Sprint 03 Part B) --- read-only; the nightly
    // `predict-risk` job owns the data, no mutation route exists (P21/P2).
    listPredictions: {
      method: "GET",
      path: "/v1/predictions",
      query: PageQuery.extend({
        subjectKind: PredictionSubjectKind.optional(),
        horizon: z.string().min(1).max(32).optional(),
        order: z.enum(["predicted_value", "created_at"]).optional(),
      }),
      responses: { 200: page(RiskPredictionDto), ...commonErrors },
      summary: "List predictions (cursor-paginated; rank by predicted_value or recency)",
    },
    getPrediction: {
      method: "GET",
      path: "/v1/predictions/:subjectKind/:id",
      pathParams: z.object({ subjectKind: PredictionSubjectKind, id: z.string().uuid() }),
      responses: { 200: PredictionDetailResponse, ...commonErrors },
      summary: "Fetch one subject's full history + forecast across all horizons",
    },

    // --- AI gateway (06 §3) ------------------------------------------------
    requestAiDraft: {
      method: "POST",
      path: "/v1/ai/drafts",
      body: AiDraftRequest,
      // 402: pack inactive or budget exhausted; 503: model provider unavailable.
      responses: { 200: AiDraftDto, 402: ErrorBody, 503: ErrorBody, ...commonErrors },
      summary: "Request an AI draft through the governed gateway (never writes an entity)",
    },
    acceptAiSummary: {
      method: "POST",
      path: "/v1/ai/summaries/accept",
      body: AcceptAiSummaryBody,
      responses: { 200: AiSummaryDto, ...commonErrors },
      summary: "Accept an AI-drafted summary onto a document (records ai_draft_accepted)",
    },

    // --- CAPAs -------------------------------------------------------------
    listCapas: {
      method: "GET",
      path: "/v1/capas",
      query: PageQuery.extend({
        status: CapaPhase.optional(),
        type: CapaType.optional(),
        priority: NcrPriority.optional(),
      }),
      responses: { 200: page(CapaDto), ...commonErrors },
      summary: "List CAPAs (cursor-paginated)",
    },
    createCapa: {
      method: "POST",
      path: "/v1/capas",
      body: CreateCapaBody,
      responses: { 201: CapaDto, ...commonErrors },
      summary: "Open a CAPA",
    },
    getCapa: {
      method: "GET",
      path: "/v1/capas/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: CapaDto, ...commonErrors },
      summary: "Fetch one CAPA",
    },
    advanceCapa: {
      method: "POST",
      path: "/v1/capas/:id/advance",
      pathParams: z.object({ id: z.string().uuid() }),
      body: AdvanceCapaBody,
      responses: { 200: CapaDto, ...commonErrors },
      summary: "Advance a CAPA one phase forward",
    },
    revertCapa: {
      method: "POST",
      path: "/v1/capas/:id/revert",
      pathParams: z.object({ id: z.string().uuid() }),
      body: RevertCapaBody,
      responses: { 200: CapaDto, ...commonErrors },
      summary: "Revert a CAPA to an earlier phase (audited, reason required)",
    },
    assignCapa: {
      method: "POST",
      path: "/v1/capas/:id/assign",
      pathParams: z.object({ id: z.string().uuid() }),
      body: AssignCapaBody,
      responses: { 200: CapaDto, ...commonErrors },
      summary: "Assign, reassign, or clear a CAPA's owner and/or sponsor (audited)",
    },

    // --- CAPA actions ------------------------------------------------------
    listCapaActions: {
      method: "GET",
      path: "/v1/capas/:id/actions",
      pathParams: z.object({ id: z.string().uuid() }),
      query: PageQuery,
      responses: { 200: page(CapaActionDto), ...commonErrors },
      summary: "List a CAPA's actions",
    },
    createCapaAction: {
      method: "POST",
      path: "/v1/capas/:id/actions",
      pathParams: z.object({ id: z.string().uuid() }),
      body: CreateCapaActionBody,
      responses: { 201: CapaActionDto, ...commonErrors },
      summary: "Add an action to a CAPA",
    },
    updateCapaActionStatus: {
      method: "POST",
      path: "/v1/capa-actions/:id/status",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdateCapaActionStatusBody,
      responses: { 200: CapaActionDto, ...commonErrors },
      summary: "Advance a CAPA action's status (pending → in_progress → done → verified)",
    },

    // --- Documents ---------------------------------------------------------
    listDocuments: {
      method: "GET",
      path: "/v1/documents",
      query: PageQuery.extend({
        status: DocumentStatus.optional(),
        category: DocumentCategory.optional(),
      }),
      responses: { 200: page(DocumentDto), ...commonErrors },
      summary: "List documents (cursor-paginated)",
    },
    createDocument: {
      method: "POST",
      path: "/v1/documents",
      body: CreateDocumentBody,
      responses: { 201: DocumentDto, ...commonErrors },
      summary: "Create a document (draft, version 1.0)",
    },
    getDocument: {
      method: "GET",
      path: "/v1/documents/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: DocumentDto, ...commonErrors },
      summary: "Fetch one document",
    },
    transitionDocument: {
      method: "POST",
      path: "/v1/documents/:id/transition",
      pathParams: z.object({ id: z.string().uuid() }),
      body: TransitionDocumentBody,
      responses: { 200: DocumentDto, ...commonErrors },
      summary: "Author-side lifecycle: submit (→pending), revise (rejected→draft), archive",
    },
    reviewDocument: {
      method: "POST",
      path: "/v1/documents/:id/review",
      pathParams: z.object({ id: z.string().uuid() }),
      body: ReviewDocumentBody,
      responses: { 200: DocumentDto, ...commonErrors },
      summary: "Approve or reject a pending document (four-eyes: not the author)",
    },
    listDocumentVersions: {
      method: "GET",
      path: "/v1/documents/:id/versions",
      pathParams: z.object({ id: z.string().uuid() }),
      query: PageQuery,
      responses: { 200: page(DocumentVersionDto), ...commonErrors },
      summary: "List a document's version history",
    },
    newDocumentVersion: {
      method: "POST",
      path: "/v1/documents/:id/versions",
      pathParams: z.object({ id: z.string().uuid() }),
      body: NewDocumentVersionBody,
      responses: { 201: DocumentDto, ...commonErrors },
      summary: "Open a new draft version of an approved document",
    },

    // --- Collaboration: comments, links, access log ------------------------
    listComments: {
      method: "GET",
      path: "/v1/comments",
      query: EntityRefQuery.merge(PageQuery),
      responses: { 200: page(CommentDto), ...commonErrors },
      summary: "List a record's comments (cursor-paginated, newest first)",
    },
    createComment: {
      method: "POST",
      path: "/v1/comments",
      body: CreateCommentBody,
      responses: { 201: CommentDto, ...commonErrors },
      summary: "Post a comment on a record (audited as 'commented' on the record)",
    },
    deleteComment: {
      method: "POST",
      path: "/v1/comments/:id/delete",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: CommentDto, ...commonErrors },
      summary: "Soft-delete one of your own comments",
    },
    listAuditEvents: {
      method: "GET",
      path: "/v1/audit-events",
      query: EntityRefQuery.merge(PageQuery),
      responses: { 200: page(AuditEventDto), ...commonErrors },
      summary: "A record's access log (audit events, newest first; no payloads)",
    },
    listTenantAuditLog: {
      method: "GET",
      path: "/v1/audit-log",
      query: AuditLogQuery,
      responses: { 200: page(AuditLogEntryDto), ...commonErrors },
      summary: "Tenant-wide audit log (admin only; filterable, newest first, no payloads)",
    },
    listEntityLinks: {
      method: "GET",
      path: "/v1/entity-links",
      query: EntityRefQuery,
      responses: { 200: page(EntityLinkDto), ...commonErrors },
      summary: "List records linked to this record (either direction)",
    },
    createEntityLink: {
      method: "POST",
      path: "/v1/entity-links",
      body: CreateEntityLinkBody,
      responses: { 201: EntityLinkDto, ...commonErrors },
      summary: "Link two records (both must resolve within the tenant)",
    },
    deleteEntityLink: {
      method: "POST",
      path: "/v1/entity-links/:id/delete",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: EntityLinkDto, ...commonErrors },
      summary: "Remove a link between two records",
    },

    // --- Settings: white-label branding ------------------------------------
    getBranding: {
      method: "GET",
      path: "/v1/settings/branding",
      responses: { 200: BrandingDto, ...commonErrors },
      summary: "This workspace's white-label branding (defaults-merged, read by the shell)",
    },
    updateBranding: {
      method: "PUT",
      path: "/v1/settings/branding",
      body: UpdateBrandingBody,
      responses: { 200: BrandingDto, ...commonErrors },
      summary: "Save this workspace's white-label branding (settings:manage; optimistic)",
    },

    // --- Settings: session policy ------------------------------------------
    getSessionPolicy: {
      method: "GET",
      path: "/v1/settings/session-policy",
      responses: { 200: SessionPolicyDto, ...commonErrors },
      summary: "This workspace's session policy (defaults-merged)",
    },
    updateSessionPolicy: {
      method: "PUT",
      path: "/v1/settings/session-policy",
      body: UpdateSessionPolicyBody,
      responses: { 200: SessionPolicyDto, ...commonErrors },
      summary: "Save this workspace's session policy (settings:manage; optimistic)",
    },

    // --- Settings: NCR validation rules ------------------------------------
    listNcrValidationRules: {
      method: "GET",
      path: "/v1/settings/ncr-validation-rules",
      responses: { 200: page(NcrValidationRuleDto), ...commonErrors },
      summary: "The NCR validation rules enforced on NCR create",
    },
    createNcrValidationRule: {
      method: "POST",
      path: "/v1/settings/ncr-validation-rules",
      body: CreateNcrValidationRuleBody,
      responses: { 201: NcrValidationRuleDto, ...commonErrors },
      summary: "Add an NCR validation rule (settings:manage)",
    },
    updateNcrValidationRule: {
      method: "PUT",
      path: "/v1/settings/ncr-validation-rules/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdateNcrValidationRuleBody,
      responses: { 200: NcrValidationRuleDto, ...commonErrors },
      summary: "Edit an NCR validation rule (settings:manage; optimistic)",
    },
    deleteNcrValidationRule: {
      method: "POST",
      path: "/v1/settings/ncr-validation-rules/:id/delete",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: NcrValidationRuleDto, ...commonErrors },
      summary: "Remove an NCR validation rule (settings:manage)",
    },

    // --- Settings: legal hold register -------------------------------------
    listLegalHolds: {
      method: "GET",
      path: "/v1/settings/legal-holds",
      responses: { 200: page(LegalHoldDto), ...commonErrors },
      summary: "This workspace's legal-hold register",
    },
    createLegalHold: {
      method: "POST",
      path: "/v1/settings/legal-holds",
      body: CreateLegalHoldBody,
      responses: { 201: LegalHoldDto, ...commonErrors },
      summary: "Open a legal hold (settings:manage)",
    },
    updateLegalHold: {
      method: "PUT",
      path: "/v1/settings/legal-holds/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdateLegalHoldBody,
      responses: { 200: LegalHoldDto, ...commonErrors },
      summary: "Edit a legal hold (settings:manage; optimistic)",
    },
    releaseLegalHold: {
      method: "POST",
      path: "/v1/settings/legal-holds/:id/release",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({ version: z.number().int().nonnegative() }),
      responses: { 200: LegalHoldDto, ...commonErrors },
      summary: "Release a legal hold (settings:manage; optimistic)",
    },
    deleteLegalHold: {
      method: "POST",
      path: "/v1/settings/legal-holds/:id/delete",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: LegalHoldDto, ...commonErrors },
      summary: "Remove a legal hold from the register (settings:manage)",
    },

    // --- Settings: DLP policy register -------------------------------------
    listDlpPolicies: {
      method: "GET",
      path: "/v1/settings/dlp-policies",
      responses: { 200: page(DlpPolicyDto), ...commonErrors },
      summary: "This workspace's DLP policy register",
    },
    createDlpPolicy: {
      method: "POST",
      path: "/v1/settings/dlp-policies",
      body: CreateDlpPolicyBody,
      responses: { 201: DlpPolicyDto, ...commonErrors },
      summary: "Add a DLP policy (settings:manage)",
    },
    updateDlpPolicy: {
      method: "PUT",
      path: "/v1/settings/dlp-policies/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdateDlpPolicyBody,
      responses: { 200: DlpPolicyDto, ...commonErrors },
      summary: "Edit a DLP policy (settings:manage; optimistic)",
    },
    deleteDlpPolicy: {
      method: "POST",
      path: "/v1/settings/dlp-policies/:id/delete",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: DlpPolicyDto, ...commonErrors },
      summary: "Remove a DLP policy (settings:manage)",
    },

    // --- Settings: cost centers + chargeback -------------------------------
    listCostCenters: {
      method: "GET",
      path: "/v1/settings/cost-centers",
      responses: { 200: page(CostCenterDto), ...commonErrors },
      summary: "This workspace's cost-center hierarchy (with seat counts)",
    },
    createCostCenter: {
      method: "POST",
      path: "/v1/settings/cost-centers",
      body: CreateCostCenterBody,
      responses: { 201: CostCenterDto, ...commonErrors },
      summary: "Add a cost center (settings:manage)",
    },
    updateCostCenter: {
      method: "PUT",
      path: "/v1/settings/cost-centers/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdateCostCenterBody,
      responses: { 200: CostCenterDto, ...commonErrors },
      summary: "Edit a cost center (settings:manage; optimistic)",
    },
    deleteCostCenter: {
      method: "POST",
      path: "/v1/settings/cost-centers/:id/delete",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: CostCenterDto, ...commonErrors },
      summary: "Remove a cost center (settings:manage; must have no children)",
    },
    listCostCenterAssignments: {
      method: "GET",
      path: "/v1/settings/cost-centers/assignments",
      responses: { 200: page(CostCenterAssignmentDto), ...commonErrors },
      summary: "Tenant members and their cost-center assignment",
    },
    assignCostCenter: {
      method: "POST",
      path: "/v1/settings/cost-centers/assign",
      body: AssignCostCenterBody,
      responses: { 200: CostCenterAssignmentDto, ...commonErrors },
      summary: "Assign a member to a cost center (settings:manage)",
    },
    getChargebackSettings: {
      method: "GET",
      path: "/v1/settings/chargeback",
      responses: { 200: ChargebackSettingsDto, ...commonErrors },
      summary: "This workspace's chargeback allocation settings (defaults-merged)",
    },
    updateChargebackSettings: {
      method: "PUT",
      path: "/v1/settings/chargeback",
      body: UpdateChargebackSettingsBody,
      responses: { 200: ChargebackSettingsDto, ...commonErrors },
      summary: "Save chargeback allocation settings (settings:manage; optimistic)",
    },
    getChargebackReport: {
      method: "GET",
      path: "/v1/settings/chargeback/report",
      responses: { 200: ChargebackReportDto, ...commonErrors },
      summary: "The current-month chargeback, allocated across cost centers (conserved)",
    },

    // --- FMEA workbench ----------------------------------------------------
    listFmeas: {
      method: "GET",
      path: "/v1/fmeas",
      responses: { 200: page(FmeaDto), ...commonErrors },
      summary: "The workspace's FMEAs (fmea:view)",
    },
    createFmea: {
      method: "POST",
      path: "/v1/fmeas",
      body: CreateFmeaBody,
      responses: { 201: FmeaDto, ...commonErrors },
      summary: "Create an FMEA (fmea:manage)",
    },
    getFmea: {
      method: "GET",
      path: "/v1/fmeas/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: FmeaDto, ...commonErrors },
      summary: "One FMEA header (fmea:view)",
    },
    updateFmea: {
      method: "PUT",
      path: "/v1/fmeas/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdateFmeaBody,
      responses: { 200: FmeaDto, ...commonErrors },
      summary: "Edit an FMEA header (fmea:manage; optimistic)",
    },
    deleteFmea: {
      method: "POST",
      path: "/v1/fmeas/:id/delete",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: FmeaDto, ...commonErrors },
      summary: "Delete an FMEA and its failure modes (fmea:manage)",
    },
    listFmeaItems: {
      method: "GET",
      path: "/v1/fmeas/:id/items",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: page(FmeaItemDto), ...commonErrors },
      summary: "An FMEA's failure modes, scored (fmea:view)",
    },
    createFmeaItem: {
      method: "POST",
      path: "/v1/fmeas/:id/items",
      pathParams: z.object({ id: z.string().uuid() }),
      body: CreateFmeaItemBody,
      responses: { 201: FmeaItemDto, ...commonErrors },
      summary: "Add a failure mode (fmea:manage)",
    },
    updateFmeaItem: {
      method: "PUT",
      path: "/v1/fmeas/:id/items/:itemId",
      pathParams: z.object({ id: z.string().uuid(), itemId: z.string().uuid() }),
      body: UpdateFmeaItemBody,
      responses: { 200: FmeaItemDto, ...commonErrors },
      summary: "Edit a failure mode (fmea:manage; optimistic)",
    },
    deleteFmeaItem: {
      method: "POST",
      path: "/v1/fmeas/:id/items/:itemId/delete",
      pathParams: z.object({ id: z.string().uuid(), itemId: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: FmeaItemDto, ...commonErrors },
      summary: "Remove a failure mode (fmea:manage)",
    },

    // --- Risk register (Sprint 04 R1/R2) ------------------------------------
    listRisks: {
      method: "GET",
      path: "/v1/risks",
      query: RiskListQuery,
      responses: { 200: page(RiskDto), ...commonErrors },
      summary: "The risk register, cursor-paginated (risk:view); `ids` batch-resolves specific risks",
    },
    getRisksSummary: {
      method: "GET",
      path: "/v1/risks/summary",
      responses: { 200: RiskSummaryDto, ...commonErrors },
      summary:
        "Unpaginated KPI/heat-map/category aggregate over ALL the caller's visible risks (risk:view) — architect-flagged addition, a paginated list cannot supply this (rule 6)",
    },
    createRisk: {
      method: "POST",
      path: "/v1/risks",
      body: CreateRiskBody,
      responses: { 201: RiskDto, ...commonErrors },
      summary: "Raise a risk (risk:manage)",
    },
    getRisk: {
      method: "GET",
      path: "/v1/risks/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: RiskDto, ...commonErrors },
      summary: "One risk, with its controls (risk:view)",
    },
    updateRisk: {
      method: "PATCH",
      path: "/v1/risks/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdateRiskBody,
      responses: { 200: RiskDto, ...commonErrors },
      summary: "Edit a risk, incl. Re-score and a full controls[] replace (risk:manage; optimistic)",
    },

    // --- MSA / Gauge R&R (Sprint 04 M1-M4) ----------------------------------
    listMsaStudies: {
      method: "GET",
      path: "/v1/msa-studies",
      query: MsaListQuery,
      responses: { 200: page(MsaStudyDto), ...commonErrors },
      summary: "Recent MSA studies, draft and completed, cursor-paginated (msa:view)",
    },
    createMsaStudy: {
      method: "POST",
      path: "/v1/msa-studies",
      body: CreateMsaStudyBody,
      responses: { 201: MsaStudyDto, ...commonErrors },
      summary: "Start a new MSA study shell (draft) (msa:manage)",
    },
    getMsaStudy: {
      method: "GET",
      path: "/v1/msa-studies/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: MsaStudyDto, ...commonErrors },
      summary: "One MSA study, with its current measurement grid (msa:view)",
    },
    completeMsaStudy: {
      method: "PATCH",
      path: "/v1/msa-studies/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      body: MsaCompleteBody,
      responses: { 200: MsaStudyDto, ...commonErrors },
      summary: "Complete a fully-filled study; dimensions are immutable (msa:manage; optimistic)",
    },
    reopenMsaStudy: {
      method: "PATCH",
      path: "/v1/msa-studies/:id/reopen",
      pathParams: z.object({ id: z.string().uuid() }),
      body: MsaReopenBody,
      responses: { 200: MsaStudyDto, ...commonErrors },
      summary: "Reopen a completed study for correction (msa:manage; optimistic)",
    },
    recordMsaMeasurements: {
      method: "POST",
      path: "/v1/msa-studies/:id/measurements",
      pathParams: z.object({ id: z.string().uuid() }),
      body: MsaMeasurementBatchBody,
      responses: { 200: MsaStudyDto, ...commonErrors },
      summary: "Bulk-upsert grid cells for a draft study (msa:manage; optimistic)",
    },
    getMsaAnalysis: {
      method: "GET",
      path: "/v1/msa-studies/:id/analysis",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: MsaAnalysisResult, ...commonErrors },
      summary: "Variance components + %StudyVar + %Tolerance + ndc + verdict, recomputed on read (msa:view)",
    },

    // --- Calibration management (Sprint 05 C1-C6) ---------------------------
    listInstruments: {
      method: "GET",
      path: "/v1/instruments",
      query: InstrumentListQuery,
      responses: { 200: page(InstrumentDto), ...commonErrors },
      summary:
        "The instrument register, cursor-paginated (calibration:view); `q` searches name/code/area name; plant-scoped, no owner-exception (§3.1 item 3)",
    },
    getInstrumentsSummary: {
      method: "GET",
      path: "/v1/instruments/summary",
      responses: { 200: InstrumentSummaryDto, ...commonErrors },
      summary:
        "KPI strip aggregate over ALL the caller's visible instruments (calibration:view) — a paginated list cannot supply this (rule 6); no owner-exception",
    },
    createInstrument: {
      method: "POST",
      path: "/v1/instruments",
      body: CreateInstrumentBody,
      responses: { 201: InstrumentDto, ...commonErrors },
      summary: "Register a new instrument (calibration:manage); code is server-assigned CAL-YYYY-NNNN",
    },
    getInstrument: {
      method: "GET",
      path: "/v1/instruments/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: InstrumentDto, ...commonErrors },
      summary:
        "One instrument (calibration:view) — the owner-sees-own-instrument plant-scope exception applies here (§3.1 item 3)",
    },
    updateInstrument: {
      method: "PATCH",
      path: "/v1/instruments/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdateInstrumentBody,
      responses: { 200: InstrumentDto, ...commonErrors },
      summary:
        "Edit an instrument, incl. Transfer (plantId/areaId only) (calibration:manage; optimistic); 422 if retired",
    },
    retireInstrument: {
      method: "PATCH",
      path: "/v1/instruments/:id/retire",
      pathParams: z.object({ id: z.string().uuid() }),
      body: RetireInstrumentBody,
      responses: { 200: InstrumentDto, ...commonErrors },
      summary: "One-way active -> retired (calibration:manage; optimistic); 422 if already retired",
    },
    listCalibrationEvents: {
      method: "GET",
      path: "/v1/instruments/:id/calibration-events",
      pathParams: z.object({ id: z.string().uuid() }),
      query: CalibrationEventListQuery,
      responses: { 200: page(CalibrationEventDto), ...commonErrors },
      summary:
        "Full calibration history, cursor-paginated (calibration:view); the detail card's \"last 5\" is `limit=5` of this route; carries the same owner-exception as the parent instrument's DETAIL fetch",
    },
    recordCalibrationEvent: {
      method: "POST",
      path: "/v1/instruments/:id/calibration-events",
      pathParams: z.object({ id: z.string().uuid() }),
      body: CreateCalibrationEventBody,
      responses: { 201: CalibrationEventDto, ...commonErrors },
      summary:
        "Record a calibration event (calibration:manage; lockVersion on the parent, optimistic); pass/adjusted advance the due date, fail never does (B3); 422 if the instrument is retired or performedAt is in the future",
    },
    attachCalibrationCertificate: {
      method: "PUT",
      path: "/v1/instruments/:instrumentId/calibration-events/:eventId/certificate",
      pathParams: z.object({ instrumentId: z.string().uuid(), eventId: z.string().uuid() }),
      body: AttachCertificateBody,
      responses: { 200: CalibrationEventDto, ...commonErrors },
      summary:
        "Attach/replace a calibration event's certificate after the fact (calibration:manage); verifies tenant + sha256 + entityKind='calibration_event' + not-deleted before linking",
    },
    raiseNcrFromCalibrationEvent: {
      method: "POST",
      path: "/v1/instruments/:instrumentId/calibration-events/:eventId/raise-ncr",
      pathParams: z.object({ instrumentId: z.string().uuid(), eventId: z.string().uuid() }),
      body: RaiseNcrFromCalibrationBody,
      responses: { 201: NcrDto, ...commonErrors },
      summary:
        "Raise a real NCR from an out-of-tolerance calibration event (calibration:manage on the route; ncr:create in-service, redundant-but-harmless); 422 on a passing event, 409 if already linked",
    },

    // --- Training & competency (Sprint 05 T1-T5) ----------------------------
    listCompetencies: {
      method: "GET",
      path: "/v1/competencies",
      query: CompetencyListQuery,
      responses: { 200: page(CompetencyDto), ...commonErrors },
      summary: "The tenant's competency catalog, cursor-paginated (training:view); excludes archived rows by default",
    },
    createCompetency: {
      method: "POST",
      path: "/v1/competencies",
      body: CreateCompetencyBody,
      responses: { 201: CompetencyDto, ...commonErrors },
      summary: "Author a new competency (training:manage); seq appended to the end; 409 on a code clash",
    },
    getCompetency: {
      method: "GET",
      path: "/v1/competencies/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: CompetencyDto, ...commonErrors },
      summary: "One competency (training:view)",
    },
    updateCompetency: {
      method: "PATCH",
      path: "/v1/competencies/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdateCompetencyBody,
      responses: { 200: CompetencyDto, ...commonErrors },
      summary: "Edit a competency, incl. flipping mandatory (training:manage; optimistic)",
    },
    archiveCompetency: {
      method: "PATCH",
      path: "/v1/competencies/:id/archive",
      pathParams: z.object({ id: z.string().uuid() }),
      body: ArchiveCompetencyBody,
      responses: { 200: CompetencyDto, ...commonErrors },
      summary:
        "Archive a competency — drops it from the matrix/KPIs/gaps/notification jobs, keeps every historical training record readable (training:manage; optimistic); 422 if already archived",
    },
    unarchiveCompetency: {
      method: "PATCH",
      path: "/v1/competencies/:id/unarchive",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UnarchiveCompetencyBody,
      responses: { 200: CompetencyDto, ...commonErrors },
      summary:
        "Un-archive a competency, seq reset to the end of the current order (training:manage; optimistic); 422 if not archived, 409 on a code clash",
    },
    reorderCompetencies: {
      method: "PUT",
      path: "/v1/competencies/order",
      body: ReorderCompetenciesBody,
      responses: { 200: ReorderCompetenciesResult, ...commonErrors },
      summary:
        "Atomically reorder the catalog (training:manage); body is the full ordered id array; 409 if it doesn't exactly match the current non-archived id set",
    },
    getTrainingMatrix: {
      method: "GET",
      path: "/v1/training/matrix",
      query: TrainingMatrixQuery,
      responses: { 200: page(TrainingMatrixRowDto), ...commonErrors },
      summary:
        "Members x competencies matrix, cursor-paginated over MEMBERS (training:view); `q` resolves via control.users; plant-scoped",
    },
    getTrainingSummary: {
      method: "GET",
      path: "/v1/training/summary",
      responses: { 200: TrainingSummaryDto, ...commonErrors },
      summary: "KPI strip aggregate over the caller's visible members (training:view); coverage is null when no mandatory competencies exist",
    },
    getTrainingGaps: {
      method: "GET",
      path: "/v1/training/gaps",
      query: TrainingGapsQuery,
      responses: { 200: page(TrainingGapDto), ...commonErrors },
      summary: "Every (member, competency) pair in gap/overdue/warn, worst-first, cursor-paginated (training:view)",
    },
    recordTraining: {
      method: "POST",
      path: "/v1/training/records",
      body: CreateTrainingRecordBody,
      responses: { 201: CreateTrainingRecordResult, ...commonErrors },
      summary:
        "Record a training completion for one or more members, one all-or-nothing batch (training:manage); 422 if completedAt is in the future",
    },
    listTrainingRecords: {
      method: "GET",
      path: "/v1/training/records",
      query: TrainingRecordsQuery,
      responses: { 200: page(TrainingRecordDto), ...commonErrors },
      summary:
        "A member's full training history, cursor-paginated, including archived-competency rows (memberId required); training:manage sees any member's, training:view-only sees only their own (403 otherwise)",
    },
    getTrainingRecord: {
      method: "GET",
      path: "/v1/training/records/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: TrainingRecordDto, ...commonErrors },
      summary: "One training record with its evidence link, same visibility rule as the list route",
    },

    // --- Customer complaints (Sprint 06 C1-C4, P18) -------------------------
    listComplaints: {
      method: "GET",
      path: "/v1/complaints",
      query: ComplaintListQuery,
      responses: { 200: page(ComplaintDto), ...commonErrors },
      summary:
        "The complaint register, cursor-paginated (complaint:view); `unlinked` matches ncr_id IS NULL specifically (§0 B8d); `q` searches subject/description/customer",
    },
    getComplaintsSummary: {
      method: "GET",
      path: "/v1/complaints/summary",
      responses: { 200: ComplaintSummaryDto, ...commonErrors },
      summary:
        "KPI strip + the 4 filter tabs' own counts (complaint:view) — a cursor-paginated list cannot supply these (rule 6)",
    },
    createComplaint: {
      method: "POST",
      path: "/v1/complaints",
      body: CreateComplaintBody,
      responses: { 201: ComplaintDto, ...commonErrors },
      summary:
        "Log a complaint (complaint:manage; Idempotency-Key); code is server-assigned COM-YYYY-NNNN, receivedAt always now(), SLA targets denormalized from the severity matrix at creation",
    },
    getComplaint: {
      method: "GET",
      path: "/v1/complaints/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: ComplaintDto, ...commonErrors },
      summary: "One complaint (complaint:view)",
    },
    updateComplaint: {
      method: "PATCH",
      path: "/v1/complaints/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdateComplaintBody,
      responses: { 200: ComplaintDto, ...commonErrors },
      summary:
        "Edit a complaint (complaint:manage; optimistic); remains editable after closed (§0 S4); changing severity re-derives the SLA targets in the same transaction (§0 B7c); never touches status/ncrId/eightDId/capaId/owner/acknowledgedAt/closedAt directly",
    },
    acknowledgeComplaint: {
      method: "POST",
      path: "/v1/complaints/:id/acknowledge",
      pathParams: z.object({ id: z.string().uuid() }),
      body: AcknowledgeComplaintBody,
      responses: { 200: ComplaintDto, ...commonErrors },
      summary: "Set acknowledgedAt=now() once (complaint:manage; optimistic); 422 if already acknowledged",
    },
    closeComplaint: {
      method: "POST",
      path: "/v1/complaints/:id/close",
      pathParams: z.object({ id: z.string().uuid() }),
      body: CloseComplaintBody,
      responses: { 200: ComplaintDto, ...commonErrors },
      summary:
        "Close a complaint from any non-closed status, with or without ever converting (complaint:manage; optimistic); 422 if already closed",
    },
    convertComplaint: {
      method: "POST",
      path: "/v1/complaints/:id/convert",
      pathParams: z.object({ id: z.string().uuid() }),
      body: ComplaintConvertBody,
      responses: { 200: ComplaintConvertResult, ...commonErrors },
      summary:
        "Convert/link to NCR (create new or link existing, §0 B8c), 8D, or CAPA (discriminated union on target, §0 B6g) — complaint:manage PLUS the real target capability (ncr:create/ncr:manage/capa:manage, §0 B6f); SELECT...FOR UPDATE + lockVersion + status<>'closed' guard (§0 B6a/b); status advances to rank-max, never backward; audited on every call, even when status doesn't move (§0 B6d)",
    },

    // --- Engineering Change Notices (Sprint 06 E1-E5, P19) ------------------
    listEcns: {
      method: "GET",
      path: "/v1/ecns",
      query: EcnListQuery,
      responses: { 200: page(EcnDto), ...commonErrors },
      summary:
        "The ECN register, cursor-paginated (ecn:view); includes linkedDocumentCount/autoReviseResult (§0 B8a/B3e)",
    },
    getEcnsSummary: {
      method: "GET",
      path: "/v1/ecns/summary",
      responses: { 200: EcnSummaryDto, ...commonErrors },
      summary:
        "Kanban column counts, count(*) group by stage, all 9 stage keys always present incl. ppap (ecn:view) — feeds E2's board",
    },
    createEcn: {
      method: "POST",
      path: "/v1/ecns",
      body: CreateEcnBody,
      responses: { 201: EcnDto, ...commonErrors },
      summary:
        "Create an ECN at stage:'draft' (ecn:manage; Idempotency-Key); code is server-assigned ECN-YYYY-NNNN; the 5 ecn_approvals rows are pre-created pending in the same transaction (E4 AC1)",
    },
    getEcn: {
      method: "GET",
      path: "/v1/ecns/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: EcnDto, ...commonErrors },
      summary: "One ECN (ecn:view)",
    },
    updateEcn: {
      method: "PATCH",
      path: "/v1/ecns/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdateEcnBody,
      responses: { 200: EcnDto, ...commonErrors },
      summary:
        "Edit an ECN (ecn:manage; optimistic); changeType/changeRisk/owner only while stage='draft' incl. a draft reached via resubmit (§0 B2/§0b D3), 422 otherwise; rejected entirely (422) once stage is closed or rejected; never sets stage directly",
    },
    submitEcn: {
      method: "POST",
      path: "/v1/ecns/:id/submit",
      pathParams: z.object({ id: z.string().uuid() }),
      body: EcnLifecycleBody,
      responses: { 200: EcnDto, ...commonErrors },
      summary:
        "draft -> feasibility (ecn:manage; optimistic); 422 if not currently draft; notifies every ecn:approve holder except owner/created_by (§0 S7)",
    },
    withdrawEcn: {
      method: "POST",
      path: "/v1/ecns/:id/withdraw",
      pathParams: z.object({ id: z.string().uuid() }),
      body: EcnLifecycleBody,
      responses: { 200: EcnDto, ...commonErrors },
      summary:
        "draft -> rejected (ecn:manage; optimistic) — an author cancelling their own draft, no four-eyes decision since no ecn_approvals row exists yet at draft",
    },
    resubmitEcn: {
      method: "POST",
      path: "/v1/ecns/:id/resubmit",
      pathParams: z.object({ id: z.string().uuid() }),
      body: EcnLifecycleBody,
      responses: { 200: EcnDto, ...commonErrors },
      summary:
        "rejected -> draft (ecn:manage, not owner-restricted; optimistic, §0b D3); 422 if not currently rejected; resets all 5 ecn_approvals rows to pending in the same transaction; owner becomes PATCHable again",
    },
    closeEcn: {
      method: "POST",
      path: "/v1/ecns/:id/close",
      pathParams: z.object({ id: z.string().uuid() }),
      body: EcnLifecycleBody,
      responses: { 200: EcnDto, ...commonErrors },
      summary: "implementation -> closed (ecn:manage; optimistic); not a four-eyes decision",
    },
    listEcnApprovals: {
      method: "GET",
      path: "/v1/ecns/:id/approvals",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: z.array(EcnApprovalDto), ...commonErrors },
      summary: "The 5-row approval tracker for the detail view (ecn:view), incl. ppap",
    },
    decideEcnApproval: {
      method: "POST",
      path: "/v1/ecns/:id/approvals/:stage",
      pathParams: z.object({ id: z.string().uuid(), stage: EcnApprovalStage }),
      body: DecideEcnApprovalBody,
      responses: { 200: EcnDto, ...commonErrors },
      summary:
        "Approve or reject the ECN's current gated stage (ecn:approve, admin/manager only; optimistic) — four-eyes folded into the transition's own WHERE clause (owner/created_by excluded, both decisions, §3 round-3 review item a); 422 if :stage is not the current pending stage; reject requires a comment; approving pilot->implementation runs E5's auto-revise in the same transaction",
    },
    listEcnLinks: {
      method: "GET",
      path: "/v1/ecns/:id/links",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: z.array(EcnLinkDto), ...commonErrors },
      summary: "Affected documents/suppliers linked to this ECN (ecn:view)",
    },
    linkEcn: {
      method: "POST",
      path: "/v1/ecns/:id/link",
      pathParams: z.object({ id: z.string().uuid() }),
      body: EcnLinkBody,
      responses: { 201: EcnLinkDto, ...commonErrors },
      summary:
        "Link an affected document or supplier (ecn:manage; SELECT...FOR SHARE on the parent first, §0 S2); 422 once stage is implementation/closed/rejected",
    },
    unlinkEcn: {
      method: "POST",
      path: "/v1/ecns/:id/links/:linkId/delete",
      pathParams: z.object({ id: z.string().uuid(), linkId: z.string().uuid() }),
      body: z.object({}).strict(),
      responses: { 200: EcnDto, ...commonErrors },
      summary:
        "Remove an affected-record link (ecn:manage + stage draft..pilot, else 422; SELECT...FOR SHARE on the parent first, §0 B4/§3 round-3 review item b) — the generic /v1/entity-links delete route rejects any ecn-kind link outright",
    },

    // --- Data platform: query engine (B2) ----------------------------------
    listQuerySources: {
      method: "GET",
      path: "/v1/query/sources",
      responses: { 200: QuerySourcesResult, ...commonErrors },
      summary: "Data sources the caller may query, with field schemas (source *:view)",
    },
    runQuery: {
      method: "POST",
      path: "/v1/query",
      body: Query,
      responses: { 200: QueryRowsResult, ...commonErrors },
      summary: "Run a query for rows (datatable / repeater); source *:view + RLS",
    },
    runQueryMetric: {
      method: "POST",
      path: "/v1/query/metric",
      body: Query,
      responses: { 200: QueryMetricResult, ...commonErrors },
      summary: "Run a query for a single scalar (KPI); source *:view + RLS",
    },
    runQuerySeries: {
      method: "POST",
      path: "/v1/query/series",
      body: Query,
      responses: { 200: QuerySeriesResult, ...commonErrors },
      summary: "Run a query for a grouped series (bar/pie/line); source *:view + RLS",
    },

    // --- Data platform: report definitions & dashboards (B3) ----------------
    listReports: {
      method: "GET",
      path: "/v1/reports",
      responses: { 200: page(ReportDefinitionDto), ...commonErrors },
      summary: "Saved reports + built-in dashboards (report:view)",
    },
    createReport: {
      method: "POST",
      path: "/v1/reports",
      body: CreateReportBody,
      responses: { 201: ReportDefinitionDto, ...commonErrors },
      summary: "Create a report definition (report:manage)",
    },
    getReport: {
      method: "GET",
      path: "/v1/reports/:id",
      pathParams: z.object({ id: z.string() }),
      responses: { 200: ReportDefinitionDto, ...commonErrors },
      summary: "One report or built-in dashboard by id (report:view)",
    },
    updateReport: {
      method: "PUT",
      path: "/v1/reports/:id",
      pathParams: z.object({ id: z.string() }),
      body: UpdateReportBody,
      responses: { 200: ReportDefinitionDto, ...commonErrors },
      summary: "Edit a report definition (report:manage; optimistic)",
    },
    deleteReport: {
      method: "POST",
      path: "/v1/reports/:id/delete",
      pathParams: z.object({ id: z.string() }),
      body: z.object({}),
      responses: { 200: ReportDefinitionDto, ...commonErrors },
      summary: "Delete a report definition (report:manage)",
    },

    // --- Data platform: connector registry (09 §1) -------------------------
    listIntegrations: {
      method: "GET",
      path: "/v1/integrations",
      responses: { 200: page(IntegrationDto), ...commonErrors },
      summary: "The workspace's connectors (integration:manage)",
    },
    createIntegration: {
      method: "POST",
      path: "/v1/integrations",
      body: CreateIntegrationBody,
      responses: { 201: IntegrationDto, ...commonErrors },
      summary: "Register a connector (integration:manage)",
    },
    getIntegration: {
      method: "GET",
      path: "/v1/integrations/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: IntegrationDto, ...commonErrors },
      summary: "One connector (integration:manage)",
    },
    getIntegrationSchema: {
      method: "GET",
      path: "/v1/integrations/:id/schema",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: ConnectorSchemaResult, ...commonErrors },
      summary: "A connector's declared field schema (integration:manage)",
    },
    listIntegrationEvents: {
      method: "GET",
      path: "/v1/integrations/:id/events",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: page(IntegrationEventDto), ...commonErrors },
      summary: "A connector's delivery log (integration:manage)",
    },
    updateIntegration: {
      method: "PUT",
      path: "/v1/integrations/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdateIntegrationBody,
      responses: { 200: IntegrationDto, ...commonErrors },
      summary: "Edit a connector's name/config (integration:manage; optimistic)",
    },
    connectIntegration: {
      method: "POST",
      path: "/v1/integrations/:id/connect",
      pathParams: z.object({ id: z.string().uuid() }),
      body: ConnectIntegrationBody,
      responses: { 200: IntegrationDto, ...commonErrors },
      summary: "Connect a connector — records a credential pointer (integration:manage)",
    },
    disconnectIntegration: {
      method: "POST",
      path: "/v1/integrations/:id/disconnect",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: IntegrationDto, ...commonErrors },
      summary: "Disconnect a connector — purges the credential (integration:manage)",
    },
    deleteIntegration: {
      method: "POST",
      path: "/v1/integrations/:id/delete",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: IntegrationDto, ...commonErrors },
      summary: "Remove a connector — purges secrets (integration:manage)",
    },
    getWebhookPolicy: {
      method: "GET",
      path: "/v1/integrations/webhook-policy",
      responses: { 200: WebhookPolicyDto, ...commonErrors },
      summary: "Webhook target policy for this deployment (integration:manage)",
    },
    configureWebhook: {
      method: "PUT",
      path: "/v1/integrations/:id/webhook",
      pathParams: z.object({ id: z.string().uuid() }),
      body: ConfigureWebhookBody,
      responses: { 200: ConfigureWebhookResult, ...commonErrors },
      summary: "Set a webhook's URL/events and (re)generate its signing secret (integration:manage; optimistic; secret shown once)",
    },
    testIntegration: {
      method: "POST",
      path: "/v1/integrations/:id/test",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: WebhookTestResultDto, ...commonErrors },
      summary: "Send a signed test event to a webhook endpoint (integration:manage)",
    },

    // --- Bulk import (09 §6; operations.jsx BulkImport) --------------------
    listImportTargets: {
      method: "GET",
      path: "/v1/import/targets",
      responses: { 200: ImportTargetsResult, ...commonErrors },
      summary: "Importable entities + their field schema (import:run)",
    },
    listImportProfiles: {
      method: "GET",
      path: "/v1/import/profiles",
      responses: { 200: page(ImportProfileDto), ...commonErrors },
      summary: "Saved import mappings (import:run)",
    },
    createImportProfile: {
      method: "POST",
      path: "/v1/import/profiles",
      body: CreateImportProfileBody,
      responses: { 201: ImportProfileDto, ...commonErrors },
      summary: "Save a reusable import mapping (import:run)",
    },
    deleteImportProfile: {
      method: "POST",
      path: "/v1/import/profiles/:id/delete",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: ImportProfileDto, ...commonErrors },
      summary: "Remove an import profile (import:run)",
    },
    listImportRuns: {
      method: "GET",
      path: "/v1/import/runs",
      responses: { 200: page(ImportRunDto), ...commonErrors },
      summary: "Import runs (import:run)",
    },
    createImportRun: {
      method: "POST",
      path: "/v1/import/runs",
      body: CreateImportRunBody,
      responses: { 201: ImportRunDto, ...commonErrors },
      summary: "Stage + validate + dry-run rows — nothing written (import:run)",
    },
    getImportRun: {
      method: "GET",
      path: "/v1/import/runs/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: ImportRunDto, ...commonErrors },
      summary: "One import run with counts + row results (import:run)",
    },
    commitImportRun: {
      method: "POST",
      path: "/v1/import/runs/:id/commit",
      pathParams: z.object({ id: z.string().uuid() }),
      body: CommitImportRunBody,
      responses: { 200: ImportRunDto, ...commonErrors },
      summary: "Commit a validated run — idempotent by natural key (import:run; optimistic)",
    },

    // --- SPC analytics (B5; qms-risk-spc.jsx) ------------------------------
    listSpcCharacteristics: {
      method: "GET",
      path: "/v1/spc/characteristics",
      responses: { 200: SpcCharacteristicsResult, ...commonErrors },
      summary: "Characteristics that have measurement data (spc:view)",
    },
    getSpcChart: {
      method: "GET",
      path: "/v1/spc/chart",
      query: z.object({ part: z.string(), characteristic: z.string() }),
      responses: { 200: SpcChartDto, ...commonErrors },
      summary: "X̄/R chart + Western-Electric rules + capability (spc:view)",
    },
    ingestMeasurements: {
      method: "POST",
      path: "/v1/spc/measurements",
      body: IngestMeasurementsBody,
      responses: { 201: z.object({ inserted: z.number() }), ...commonErrors },
      summary: "Ingest measurements for a characteristic (measurement:manage)",
    },

    // --- Knowledge graph explorer (Sprint 03 G1-G4; graph-explorer.jsx) ----
    listGraphSeeds: {
      method: "GET",
      path: "/v1/graph/seeds",
      responses: { 200: GraphSeedsResult, ...commonErrors },
      summary: "Up to 4 'start from a record' seed chips — most recent real record per seed kind (graph:view)",
    },
    expandGraph: {
      method: "GET",
      path: "/v1/graph/expand",
      query: z.object({
        seed: z.string().min(1),
        type: EntityKind.optional(),
        after: z.string().optional(),
      }),
      responses: { 200: GraphExpandResult, ...commonErrors },
      summary:
        "Click-to-expand neighbour reveal (graph:view). No `type`: every neighbour type " +
        "capped at 6. With `type` (+ optional `after`): that one type's next 12-item batch.",
    },
    runGraphQuery: {
      method: "GET",
      path: "/v1/graph/query/:queryId",
      pathParams: z.object({ queryId: GraphQueryId }),
      query: z.object({ focus: z.string().optional() }),
      responses: { 200: GraphQueryResult, ...commonErrors },
      summary: "One of the 4 fixed named analytical queries, capped at 60 nodes (graph:view)",
    },

    // --- Suppliers (FEATURES §11.1) ----------------------------------------
    listSuppliers: {
      method: "GET",
      path: "/v1/suppliers",
      query: PageQuery.extend({
        status: SupplierStatus.optional(),
        riskTier: RiskLevel.optional(),
        tier: z.coerce.number().int().optional(),
        category: z.string().optional(),
        country: z.string().optional(),
        flag: z.string().optional(),
        q: z.string().optional(),
      }),
      responses: { 200: page(SupplierDto), ...commonErrors },
      summary: "List suppliers (cursor-paginated; filter by tier/risk/category/country/flag/search)",
    },
    getSupplier: {
      method: "GET",
      path: "/v1/suppliers/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: SupplierDto, ...commonErrors },
      summary: "Fetch one supplier (with scorecard + profile)",
    },
    createSupplier: {
      method: "POST",
      path: "/v1/suppliers",
      body: CreateSupplierBody,
      responses: { 201: SupplierDto, ...commonErrors },
      summary: "Create a supplier",
    },
    updateSupplier: {
      method: "POST",
      path: "/v1/suppliers/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdateSupplierBody,
      responses: { 200: SupplierDto, ...commonErrors },
      summary: "Update a supplier (optimistic concurrency via version)",
    },
    scorecardSuppliers: {
      method: "GET",
      path: "/v1/supplier-scorecard",
      query: ScorecardWeightsQuery,
      responses: { 200: page(SupplierDto), ...commonErrors },
      summary: "Suppliers ranked by weighted score (PPM/OTD/OQE/SCAR weights as query params)",
    },

    // --- PPAP submissions (FEATURES §11.2) ---------------------------------
    listPpap: {
      method: "GET",
      path: "/v1/ppap",
      query: PageQuery.extend({
        supplierId: z.string().uuid().optional(),
        status: PpapStatus.optional(),
        customer: z.string().optional(),
        level: z.coerce.number().int().optional(),
        q: z.string().optional(),
      }),
      responses: { 200: page(PpapSubmissionDto), ...commonErrors },
      summary: "List PPAP submissions (cursor-paginated; filter by supplier/status/customer/level/search)",
    },
    getPpap: {
      method: "GET",
      path: "/v1/ppap/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: PpapSubmissionDto, ...commonErrors },
      summary: "Fetch one PPAP submission (with its 18 elements + completeness)",
    },
    createPpap: {
      method: "POST",
      path: "/v1/ppap",
      body: CreatePpapBody,
      responses: { 201: PpapSubmissionDto, ...commonErrors },
      summary: "Open a PPAP submission (auto-seeds the 18 elements as pending)",
    },
    updatePpap: {
      method: "POST",
      path: "/v1/ppap/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdatePpapBody,
      responses: { 200: PpapSubmissionDto, ...commonErrors },
      summary: "Update a PPAP submission (optimistic concurrency via version)",
    },
    updatePpapElement: {
      method: "POST",
      path: "/v1/ppap/:id/elements/:no",
      pathParams: z.object({ id: z.string().uuid(), no: z.coerce.number().int().min(1).max(18) }),
      body: UpdatePpapElementBody,
      responses: { 200: PpapSubmissionDto, ...commonErrors },
      summary: "Set one element's status / reviewer / comment (optimistic via version)",
    },
    decidePpap: {
      method: "POST",
      path: "/v1/ppap/:id/decision",
      pathParams: z.object({ id: z.string().uuid() }),
      body: PpapDecisionBody,
      responses: { 200: PpapSubmissionDto, ...commonErrors },
      summary: "Overall approve/reject (approve blocked until every non-N/A element is approved)",
    },

    // --- SCAR & chargebacks (FEATURES §11.3) -------------------------------
    listScars: {
      method: "GET",
      path: "/v1/scars",
      query: PageQuery.extend({
        supplierId: z.string().uuid().optional(),
        status: ScarStatus.optional(),
        severity: ScarSeverity.optional(),
        overdue: z.coerce.boolean().optional(),
        q: z.string().optional(),
      }),
      responses: { 200: page(ScarDto), ...commonErrors },
      summary: "List SCARs (cursor-paginated; filter by supplier/status/severity/overdue/search)",
    },
    getScar: {
      method: "GET",
      path: "/v1/scars/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: ScarDto, ...commonErrors },
      summary: "Fetch one SCAR",
    },
    createScar: {
      method: "POST",
      path: "/v1/scars",
      body: CreateScarBody,
      responses: { 201: ScarDto, ...commonErrors },
      summary: "Raise a SCAR against a supplier (auto-codes SCAR-YYYY-NNNN)",
    },
    updateScar: {
      method: "POST",
      path: "/v1/scars/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      body: UpdateScarBody,
      responses: { 200: ScarDto, ...commonErrors },
      summary: "Update a SCAR (optimistic concurrency via version)",
    },
    advanceScar: {
      method: "POST",
      path: "/v1/scars/:id/advance",
      pathParams: z.object({ id: z.string().uuid() }),
      body: AdvanceScarBody,
      responses: { 200: ScarDto, ...commonErrors },
      summary: "Advance the 8D one discipline forward (blocked past D8)",
    },
    acknowledgeScar: {
      method: "POST",
      path: "/v1/scars/:id/acknowledge",
      pathParams: z.object({ id: z.string().uuid() }),
      body: AcknowledgeScarBody,
      responses: { 200: ScarDto, ...commonErrors },
      summary: "Record the supplier's acknowledgement of the SCAR",
    },
    chargebackScar: {
      method: "POST",
      path: "/v1/scars/:id/chargeback",
      pathParams: z.object({ id: z.string().uuid() }),
      body: ScarChargebackBody,
      responses: { 200: ScarDto, ...commonErrors },
      summary: "Set / transition the chargeback (one-way: none→pending→debit_issued→closed)",
    },
    assignScar: {
      method: "POST",
      path: "/v1/scars/:id/assign",
      pathParams: z.object({ id: z.string().uuid() }),
      body: AssignScarBody,
      responses: { 200: ScarDto, ...commonErrors },
      summary: "Assign, reassign, or clear a SCAR's owner (audited)",
    },

    // --- Supplier portal (external, read-only; FEATURES §17) ---------------
    // Partner-only (`portal:view`), and every response is additionally scoped to
    // the caller's own supplier — a foreign id is 404, never 403.
    getPortalIdentity: {
      method: "GET",
      path: "/v1/portal/me",
      responses: { 200: PortalIdentityDto, ...commonErrors },
      summary: "The partner's own supplier identity",
    },
    listPortalScars: {
      method: "GET",
      path: "/v1/portal/scars",
      query: PageQuery,
      responses: { 200: page(PortalScarDto), ...commonErrors },
      summary: "The partner's own SCARs (cursor-paginated, scoped to their supplier)",
    },
    getPortalScar: {
      method: "GET",
      path: "/v1/portal/scars/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: PortalScarDto, ...commonErrors },
      summary: "One of the partner's own SCARs (foreign supplier → 404)",
    },
    listPortalPpap: {
      method: "GET",
      path: "/v1/portal/ppap",
      query: PageQuery,
      responses: { 200: page(PortalPpapDto), ...commonErrors },
      summary: "The partner's own PPAP submissions (cursor-paginated, scoped)",
    },
    getPortalPpap: {
      method: "GET",
      path: "/v1/portal/ppap/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: PortalPpapDto, ...commonErrors },
      summary: "One of the partner's own PPAP submissions (foreign supplier → 404)",
    },
    respondPortalScar: {
      method: "POST",
      path: "/v1/portal/scars/:id/respond",
      pathParams: z.object({ id: z.string().uuid() }),
      body: PortalScarRespondBody,
      responses: { 200: PortalScarDto, ...commonErrors },
      summary: "Supplier responds to a SCAR (note + optional acknowledge; audited actor_kind=partner)",
    },
    resubmitPortalPpap: {
      method: "POST",
      path: "/v1/portal/ppap/:id/resubmit",
      pathParams: z.object({ id: z.string().uuid() }),
      body: PortalPpapResubmitBody,
      responses: { 200: PortalPpapDto, ...commonErrors },
      summary: "Supplier re-submits a PPAP package after feedback (audited actor_kind=partner)",
    },
    // Evidence upload (P11): a partner-scoped mirror of the internal presign flow.
    // The file is created UNLINKED and owned by the caller; it is attached to one
    // of the partner's own records only via respond/re-submit `fileIds`, so a
    // partner never reaches the internal `/v1/files/*` routes or names an entity.
    presignPortalEvidence: {
      method: "POST",
      path: "/v1/portal/files/presign",
      body: PortalEvidencePresignBody,
      responses: { 201: PresignFileResult, ...commonErrors },
      summary: "Presign a portal evidence upload (partner-scoped; file created unlinked)",
    },
    completePortalEvidence: {
      method: "POST",
      path: "/v1/portal/files/:id/complete",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: FileDto, ...commonErrors },
      summary: "Finalise a portal evidence upload and hand it to the AV scan",
    },

    // --- Notifications -----------------------------------------------------
    listNotifications: {
      method: "GET",
      path: "/v1/notifications",
      query: PageQuery.extend({
        unread: z.coerce.boolean().optional(),
        starred: z.coerce.boolean().optional(),
        entityKind: z.string().max(40).optional(),
        /** Notification kind filter, e.g. `mention` for the Mentions tab. */
        type: z.string().max(40).optional(),
      }),
      responses: { 200: NotificationPageDto, ...commonErrors },
      summary: "List the current user's notifications (cursor-paginated; unread/starred/type filters)",
    },
    unreadCount: {
      method: "GET",
      path: "/v1/notifications/unread-count",
      responses: { 200: UnreadCountDto, ...commonErrors },
      summary: "The current user's unread notification count (the bell badge)",
    },
    markNotificationRead: {
      method: "POST",
      path: "/v1/notifications/:id/read",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: NotificationDto, ...commonErrors },
      summary: "Mark one of the current user's notifications read",
    },
    markAllNotificationsRead: {
      method: "POST",
      path: "/v1/notifications/read-all",
      body: z.object({}),
      responses: { 200: CountDto, ...commonErrors },
      summary: "Mark all of the current user's notifications read",
    },
    starNotification: {
      method: "POST",
      path: "/v1/notifications/:id/star",
      pathParams: z.object({ id: z.string().uuid() }),
      body: StarNotificationBody,
      responses: { 200: NotificationDto, ...commonErrors },
      summary: "Star or un-star one of the current user's notifications",
    },
    dismissNotification: {
      method: "POST",
      path: "/v1/notifications/:id/dismiss",
      pathParams: z.object({ id: z.string().uuid() }),
      body: z.object({}),
      responses: { 200: CountDto, ...commonErrors },
      summary: "Dismiss (soft-delete) one of the current user's notifications",
    },
    getNotificationPrefs: {
      method: "GET",
      path: "/v1/notification-prefs",
      responses: { 200: NotificationPrefsDto, ...commonErrors },
      summary: "The current user's per-kind channel preferences",
    },
    updateNotificationPrefs: {
      method: "PUT",
      path: "/v1/notification-prefs",
      body: UpdateNotificationPrefsBody,
      responses: { 200: NotificationPrefsDto, ...commonErrors },
      summary: "Replace the current user's notification channel matrix",
    },

    getUserPreferences: {
      method: "GET",
      path: "/v1/me/preferences",
      responses: { 200: UserPreferencesDto, ...commonErrors },
      summary: "The current user's appearance/interaction preferences (defaults when never saved)",
    },
    updateUserPreferences: {
      method: "PATCH",
      path: "/v1/me/preferences",
      body: UpdateUserPreferencesBody,
      responses: { 200: UserPreferencesDto, ...commonErrors },
      summary: "Partially update the current user's preferences (optimistic: version; audited)",
    },

    // --- Files -------------------------------------------------------------
    presignFile: {
      method: "POST",
      path: "/v1/files/presign",
      body: PresignFileBody,
      responses: { 201: PresignFileResult, ...commonErrors },
      summary: "Validate mime + size and get a presigned upload URL (file row: pending)",
    },
    completeFile: {
      method: "POST",
      path: "/v1/files/:id/complete",
      pathParams: z.object({ id: z.string().uuid() }),
      body: CompleteFileBody,
      responses: { 200: FileDto, ...commonErrors },
      summary: "Confirm the upload finished; server verifies the object and records its hash",
    },
    getFile: {
      method: "GET",
      path: "/v1/files/:id",
      pathParams: z.object({ id: z.string().uuid() }),
      responses: { 200: FileDto, ...commonErrors },
      summary: "Fetch a file's metadata",
    },
    downloadFile: {
      method: "GET",
      path: "/v1/files/:id/download",
      pathParams: z.object({ id: z.string().uuid() }),
      query: DownloadFileQuery,
      responses: { 200: DownloadFileResult, ...commonErrors },
      summary: "Get a presigned download URL (inline for preview / attachment; gated on AV scan; audited)",
    },
  },
  {
    strictStatusCodes: true,
  },
);

export type Contract = typeof contract;
