import {
  AlertTriangle,
  ArrowRight,
  Bell,
  Boxes,
  Brain,
  Building2,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ClipboardList,
  Clock,
  Cloud,
  CloudOff,
  Download,
  Eye,
  EyeOff,
  FileText,
  Flag,
  Folder,
  GitBranch,
  Globe,
  Hash,
  Hexagon,
  Home,
  Info,
  Key,
  LayoutGrid,
  LineChart,
  Lock,
  LogOut,
  Mail,
  MapPin,
  MessageSquare,
  Mic,
  Moon,
  Palette,
  Paperclip,
  Pen,
  Play,
  Plug,
  Plus,
  QrCode,
  RefreshCw,
  Search,
  Send,
  Shield,
  ShieldCheck,
  Signal,
  Smartphone,
  Sparkles,
  SquarePen,
  Sun,
  Target,
  Trash2,
  Type,
  Upload,
  User,
  Users,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react-native";

import { useTheme } from "../theme";

// Maps the design kit's icon names (project_brain/mobile/src/*) to lucide icons —
// lucide is what the web app uses, so the mark set matches pixel-for-pixel. Adding a
// new screen that references an unlisted name is a typecheck error (the union below),
// which keeps the map honest.
const ICONS = {
  alert: AlertTriangle,
  arrowRight: ArrowRight,
  bell: Bell,
  brain: Brain,
  building: Building2,
  camera: Camera,
  chat: MessageSquare,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clipboard: ClipboardList,
  clock: Clock,
  cloud: Cloud,
  cloudOff: CloudOff,
  doc: FileText,
  download: Download,
  edit: SquarePen,
  eye: Eye,
  eyeOff: EyeOff,
  flag: Flag,
  folder: Folder,
  gitBranch: GitBranch,
  globe: Globe,
  grid: LayoutGrid,
  hash: Hash,
  home: Home,
  info: Info,
  key: Key,
  lineChart: LineChart,
  lock: Lock,
  logOut: LogOut,
  logo: Hexagon,
  mail: Mail,
  mapPin: MapPin,
  mic: Mic,
  moon: Moon,
  palette: Palette,
  paperclip: Paperclip,
  pen: Pen,
  play: Play,
  plug: Plug,
  plus: Plus,
  qr: QrCode,
  refresh: RefreshCw,
  reports: Boxes,
  search: Search,
  send: Send,
  shield: Shield,
  shieldCheck: ShieldCheck,
  signal: Signal,
  smartphone: Smartphone,
  sun: Sun,
  target: Target,
  tool: Wrench,
  trash: Trash2,
  type: Type,
  upload: Upload,
  user: User,
  users: Users,
  zap: Zap,
  sparkles: Sparkles,
  x: X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export interface IconProps {
  name: IconName;
  size?: number;
  /** Stroke width (design kit uses ~1.9 for body, 2.2–2.4 for emphasis). */
  stroke?: number;
  /** Explicit color; defaults to the current text color. */
  color?: string;
}

export function Icon({ name, size = 18, stroke = 1.9, color }: IconProps) {
  const { palette } = useTheme();
  const Glyph = ICONS[name];
  return <Glyph size={size} strokeWidth={stroke} color={color ?? palette.text} />;
}
