import { randomBytes } from "node:crypto";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import pg from "pg";
import * as OTPAuth from "otpauth";
import { MfaCrypto } from "../src/auth/mfa-crypto.js";
import { MfaService } from "../src/auth/mfa.service.js";

/**
 * MFA (TOTP) — crypto at rest plus the full enrol → activate → verify → recover
 * → disable lifecycle, run against the real control-plane database with real
 * codes generated by the same TOTP the app uses.
 */

const CRYPTO = new MfaCrypto({ authSecret: "test-secret-".padEnd(32, "x"), mfaKey: randomBytes(32).toString("base64") });

let control: pg.Pool;
let userId: string;
const email = `mfa-${randomBytes(4).toString("hex")}@kaenal.test`;

beforeAll(async () => {
  control = new pg.Pool({ connectionString: process.env["DATABASE_URL"] });
  const { rows } = await control.query<{ id: string }>(
    "INSERT INTO control.users (email, name) VALUES ($1, 'MFA Test') RETURNING id",
    [email],
  );
  userId = rows[0]!.id;
});

afterAll(async () => {
  await control.query("DELETE FROM control.users WHERE id = $1", [userId]); // CASCADEs recovery codes
  await control.end();
});

function service(): MfaService {
  return new MfaService(control, CRYPTO);
}

/** Extract the live code from an enrolment URI, and a code outside the accept window. */
function codesFor(otpauthUri: string): { valid: string; wrong: string } {
  const totp = OTPAuth.URI.parse(otpauthUri) as OTPAuth.TOTP;
  const now = Date.now();
  const accepted = new Set([
    totp.generate({ timestamp: now - 30_000 }),
    totp.generate({ timestamp: now }),
    totp.generate({ timestamp: now + 30_000 }),
  ]);
  let wrong = "000000";
  for (let i = 0; i < 20; i++) {
    const candidate = String(i).padStart(6, "0");
    if (!accepted.has(candidate)) {
      wrong = candidate;
      break;
    }
  }
  return { valid: totp.generate({ timestamp: now }), wrong };
}

describe("MfaCrypto — AES-256-GCM at rest", () => {
  it("round-trips a secret", () => {
    const blob = CRYPTO.encrypt("JBSWY3DPEHPK3PXP");
    expect(blob).not.toContain("JBSWY3DPEHPK3PXP");
    expect(CRYPTO.decrypt(blob)).toBe("JBSWY3DPEHPK3PXP");
  });

  it("rejects a tampered ciphertext rather than yielding garbage", () => {
    const blob = CRYPTO.encrypt("secret");
    const parts = blob.split(".");
    const tampered = `${parts[0]}.${parts[1]}.${Buffer.from("evil").toString("base64")}`;
    expect(() => CRYPTO.decrypt(tampered)).toThrow();
  });

  it("a different key cannot decrypt", () => {
    const other = new MfaCrypto({ authSecret: "x", mfaKey: randomBytes(32).toString("base64") });
    expect(() => other.decrypt(CRYPTO.encrypt("secret"))).toThrow();
  });
});

describe("MfaService — enrol → activate → verify → recover → disable", () => {
  it("walks the full lifecycle", async () => {
    const mfa = service();

    // Not enrolled to start.
    expect(await mfa.status(userId)).toMatchObject({ enrolled: false, pending: false });

    // Enrol → pending, login still unaffected (no active secret).
    const { otpauthUri, qrDataUri } = await mfa.startEnrollment(userId);
    expect(qrDataUri.startsWith("data:image/png;base64,")).toBe(true);
    expect(await mfa.status(userId)).toMatchObject({ enrolled: false, pending: true });

    // A wrong code cannot activate.
    const { valid, wrong } = codesFor(otpauthUri);
    await expect(mfa.activate(userId, wrong)).rejects.toThrow(/not valid/i);

    // The right code activates and issues 10 one-time recovery codes.
    const { recoveryCodes } = await mfa.activate(userId, valid);
    expect(recoveryCodes).toHaveLength(10);
    expect(await mfa.status(userId)).toMatchObject({ enrolled: true, pending: false, recoveryCodesRemaining: 10 });

    // A fresh TOTP verifies at login; a wrong one does not.
    expect(await mfa.verifyLogin(userId, codesFor(otpauthUri).valid)).toBe(true);
    expect(await mfa.verifyLogin(userId, wrong)).toBe(false);

    // A recovery code works once, then is spent.
    const recovery = recoveryCodes[0]!;
    expect(await mfa.verifyLogin(userId, recovery)).toBe(true);
    expect(await mfa.verifyLogin(userId, recovery)).toBe(false);
    expect((await mfa.status(userId)).recoveryCodesRemaining).toBe(9);

    // Enrolling again is refused while active.
    await expect(mfa.startEnrollment(userId)).rejects.toThrow(/already enabled/i);

    // Disable needs a valid code, then clears everything.
    await expect(mfa.disable(userId, wrong)).rejects.toThrow(/not valid/i);
    await mfa.disable(userId, codesFor(otpauthUri).valid);
    expect(await mfa.status(userId)).toMatchObject({ enrolled: false, pending: false, recoveryCodesRemaining: 0 });
  });
});
